package com.lnsoft.module.sbdzxjc.mapper;

import com.lnsoft.module.sbdzxjc.pojo.CmstLightningrod;
import com.lnsoft.module.sbdzxjc.pojo.CmstLightningrodExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmstLightningrodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMST_LIGHTNINGROD
     *
     * @mbggenerated Fri Nov 16 16:17:43 CST 2018
     */
    int countByExample(CmstLightningrodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMST_LIGHTNINGROD
     *
     * @mbggenerated Fri Nov 16 16:17:43 CST 2018
     */
    int deleteByExample(CmstLightningrodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMST_LIGHTNINGROD
     *
     * @mbggenerated Fri Nov 16 16:17:43 CST 2018
     */
    int deleteByPrimaryKey(String objId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMST_LIGHTNINGROD
     *
     * @mbggenerated Fri Nov 16 16:17:43 CST 2018
     */
    int insert(CmstLightningrod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMST_LIGHTNINGROD
     *
     * @mbggenerated Fri Nov 16 16:17:43 CST 2018
     */
    int insertSelective(CmstLightningrod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMST_LIGHTNINGROD
     *
     * @mbggenerated Fri Nov 16 16:17:43 CST 2018
     */
    List<CmstLightningrod> selectByExample(CmstLightningrodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMST_LIGHTNINGROD
     *
     * @mbggenerated Fri Nov 16 16:17:43 CST 2018
     */
    CmstLightningrod selectByPrimaryKey(String objId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMST_LIGHTNINGROD
     *
     * @mbggenerated Fri Nov 16 16:17:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") CmstLightningrod record, @Param("example") CmstLightningrodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMST_LIGHTNINGROD
     *
     * @mbggenerated Fri Nov 16 16:17:43 CST 2018
     */
    int updateByExample(@Param("record") CmstLightningrod record, @Param("example") CmstLightningrodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMST_LIGHTNINGROD
     *
     * @mbggenerated Fri Nov 16 16:17:43 CST 2018
     */
    int updateByPrimaryKeySelective(CmstLightningrod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMST_LIGHTNINGROD
     *
     * @mbggenerated Fri Nov 16 16:17:43 CST 2018
     */
    int updateByPrimaryKey(CmstLightningrod record);
}