package com.lnsoft.module.sbdzxjc.mapper;

import com.lnsoft.module.sbdzxjc.pojo.CmstAirmoisture;
import com.lnsoft.module.sbdzxjc.pojo.CmstAirmoistureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmstAirmoistureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMST_AIRMOISTURE
     *
     * @mbggenerated Fri Nov 16 16:17:43 CST 2018
     */
    int countByExample(CmstAirmoistureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMST_AIRMOISTURE
     *
     * @mbggenerated Fri Nov 16 16:17:43 CST 2018
     */
    int deleteByExample(CmstAirmoistureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMST_AIRMOISTURE
     *
     * @mbggenerated Fri Nov 16 16:17:43 CST 2018
     */
    int deleteByPrimaryKey(String objId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMST_AIRMOISTURE
     *
     * @mbggenerated Fri Nov 16 16:17:43 CST 2018
     */
    int insert(CmstAirmoisture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMST_AIRMOISTURE
     *
     * @mbggenerated Fri Nov 16 16:17:43 CST 2018
     */
    int insertSelective(CmstAirmoisture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMST_AIRMOISTURE
     *
     * @mbggenerated Fri Nov 16 16:17:43 CST 2018
     */
    List<CmstAirmoisture> selectByExample(CmstAirmoistureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMST_AIRMOISTURE
     *
     * @mbggenerated Fri Nov 16 16:17:43 CST 2018
     */
    CmstAirmoisture selectByPrimaryKey(String objId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMST_AIRMOISTURE
     *
     * @mbggenerated Fri Nov 16 16:17:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") CmstAirmoisture record, @Param("example") CmstAirmoistureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMST_AIRMOISTURE
     *
     * @mbggenerated Fri Nov 16 16:17:43 CST 2018
     */
    int updateByExample(@Param("record") CmstAirmoisture record, @Param("example") CmstAirmoistureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMST_AIRMOISTURE
     *
     * @mbggenerated Fri Nov 16 16:17:43 CST 2018
     */
    int updateByPrimaryKeySelective(CmstAirmoisture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMST_AIRMOISTURE
     *
     * @mbggenerated Fri Nov 16 16:17:43 CST 2018
     */
    int updateByPrimaryKey(CmstAirmoisture record);
}