package com.lnsoft.module.pms.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TSbDysbDyxl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.OBJ_ID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String objId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.XLMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String xlmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.DXMPYXKID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String dxmpyxkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.SBBM
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sbbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.YXBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String yxbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.BYQLX
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String byqlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.SSBYQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String ssbyq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.SSDS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String ssds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.YWDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String ywdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.WHBZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String whbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.DYDJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String dydj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.YXZT
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String yxzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.TYRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private Date tyrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.XLLX
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String xllx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.XLZCD
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal xlzcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.JKXLCD
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal jkxlcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.DLXLCD
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal dlxlcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.ZCXZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zcxz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.ZCDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zcdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.ZCBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zcbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.BZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.DJSJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private Date djsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.SBZR
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sbzr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.ZCDWMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zcdwmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.SSDSMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String ssdsmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.WHBZMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String whbzmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.YWDWMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String ywdwmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.SBZRMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sbzrmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.FBZT
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String fbzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.ZYFL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zyfl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_DYSB_DYXL.XGHSBMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String xghsbmc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.OBJ_ID
     *
     * @return the value of T_SB_DYSB_DYXL.OBJ_ID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getObjId() {
        return objId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.OBJ_ID
     *
     * @param objId the value for T_SB_DYSB_DYXL.OBJ_ID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setObjId(String objId) {
        this.objId = objId == null ? null : objId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.XLMC
     *
     * @return the value of T_SB_DYSB_DYXL.XLMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getXlmc() {
        return xlmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.XLMC
     *
     * @param xlmc the value for T_SB_DYSB_DYXL.XLMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setXlmc(String xlmc) {
        this.xlmc = xlmc == null ? null : xlmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.DXMPYXKID
     *
     * @return the value of T_SB_DYSB_DYXL.DXMPYXKID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getDxmpyxkid() {
        return dxmpyxkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.DXMPYXKID
     *
     * @param dxmpyxkid the value for T_SB_DYSB_DYXL.DXMPYXKID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setDxmpyxkid(String dxmpyxkid) {
        this.dxmpyxkid = dxmpyxkid == null ? null : dxmpyxkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.SBBM
     *
     * @return the value of T_SB_DYSB_DYXL.SBBM
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSbbm() {
        return sbbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.SBBM
     *
     * @param sbbm the value for T_SB_DYSB_DYXL.SBBM
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSbbm(String sbbm) {
        this.sbbm = sbbm == null ? null : sbbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.YXBH
     *
     * @return the value of T_SB_DYSB_DYXL.YXBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getYxbh() {
        return yxbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.YXBH
     *
     * @param yxbh the value for T_SB_DYSB_DYXL.YXBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setYxbh(String yxbh) {
        this.yxbh = yxbh == null ? null : yxbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.BYQLX
     *
     * @return the value of T_SB_DYSB_DYXL.BYQLX
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getByqlx() {
        return byqlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.BYQLX
     *
     * @param byqlx the value for T_SB_DYSB_DYXL.BYQLX
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setByqlx(String byqlx) {
        this.byqlx = byqlx == null ? null : byqlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.SSBYQ
     *
     * @return the value of T_SB_DYSB_DYXL.SSBYQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSsbyq() {
        return ssbyq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.SSBYQ
     *
     * @param ssbyq the value for T_SB_DYSB_DYXL.SSBYQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSsbyq(String ssbyq) {
        this.ssbyq = ssbyq == null ? null : ssbyq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.SSDS
     *
     * @return the value of T_SB_DYSB_DYXL.SSDS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSsds() {
        return ssds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.SSDS
     *
     * @param ssds the value for T_SB_DYSB_DYXL.SSDS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSsds(String ssds) {
        this.ssds = ssds == null ? null : ssds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.YWDW
     *
     * @return the value of T_SB_DYSB_DYXL.YWDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getYwdw() {
        return ywdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.YWDW
     *
     * @param ywdw the value for T_SB_DYSB_DYXL.YWDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setYwdw(String ywdw) {
        this.ywdw = ywdw == null ? null : ywdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.WHBZ
     *
     * @return the value of T_SB_DYSB_DYXL.WHBZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getWhbz() {
        return whbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.WHBZ
     *
     * @param whbz the value for T_SB_DYSB_DYXL.WHBZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setWhbz(String whbz) {
        this.whbz = whbz == null ? null : whbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.DYDJ
     *
     * @return the value of T_SB_DYSB_DYXL.DYDJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getDydj() {
        return dydj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.DYDJ
     *
     * @param dydj the value for T_SB_DYSB_DYXL.DYDJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setDydj(String dydj) {
        this.dydj = dydj == null ? null : dydj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.YXZT
     *
     * @return the value of T_SB_DYSB_DYXL.YXZT
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getYxzt() {
        return yxzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.YXZT
     *
     * @param yxzt the value for T_SB_DYSB_DYXL.YXZT
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setYxzt(String yxzt) {
        this.yxzt = yxzt == null ? null : yxzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.TYRQ
     *
     * @return the value of T_SB_DYSB_DYXL.TYRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public Date getTyrq() {
        return tyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.TYRQ
     *
     * @param tyrq the value for T_SB_DYSB_DYXL.TYRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setTyrq(Date tyrq) {
        this.tyrq = tyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.XLLX
     *
     * @return the value of T_SB_DYSB_DYXL.XLLX
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getXllx() {
        return xllx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.XLLX
     *
     * @param xllx the value for T_SB_DYSB_DYXL.XLLX
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setXllx(String xllx) {
        this.xllx = xllx == null ? null : xllx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.XLZCD
     *
     * @return the value of T_SB_DYSB_DYXL.XLZCD
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getXlzcd() {
        return xlzcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.XLZCD
     *
     * @param xlzcd the value for T_SB_DYSB_DYXL.XLZCD
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setXlzcd(BigDecimal xlzcd) {
        this.xlzcd = xlzcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.JKXLCD
     *
     * @return the value of T_SB_DYSB_DYXL.JKXLCD
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getJkxlcd() {
        return jkxlcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.JKXLCD
     *
     * @param jkxlcd the value for T_SB_DYSB_DYXL.JKXLCD
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setJkxlcd(BigDecimal jkxlcd) {
        this.jkxlcd = jkxlcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.DLXLCD
     *
     * @return the value of T_SB_DYSB_DYXL.DLXLCD
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getDlxlcd() {
        return dlxlcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.DLXLCD
     *
     * @param dlxlcd the value for T_SB_DYSB_DYXL.DLXLCD
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setDlxlcd(BigDecimal dlxlcd) {
        this.dlxlcd = dlxlcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.ZCXZ
     *
     * @return the value of T_SB_DYSB_DYXL.ZCXZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZcxz() {
        return zcxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.ZCXZ
     *
     * @param zcxz the value for T_SB_DYSB_DYXL.ZCXZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZcxz(String zcxz) {
        this.zcxz = zcxz == null ? null : zcxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.ZCDW
     *
     * @return the value of T_SB_DYSB_DYXL.ZCDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZcdw() {
        return zcdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.ZCDW
     *
     * @param zcdw the value for T_SB_DYSB_DYXL.ZCDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZcdw(String zcdw) {
        this.zcdw = zcdw == null ? null : zcdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.ZCBH
     *
     * @return the value of T_SB_DYSB_DYXL.ZCBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZcbh() {
        return zcbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.ZCBH
     *
     * @param zcbh the value for T_SB_DYSB_DYXL.ZCBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZcbh(String zcbh) {
        this.zcbh = zcbh == null ? null : zcbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.BZ
     *
     * @return the value of T_SB_DYSB_DYXL.BZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.BZ
     *
     * @param bz the value for T_SB_DYSB_DYXL.BZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.DJSJ
     *
     * @return the value of T_SB_DYSB_DYXL.DJSJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public Date getDjsj() {
        return djsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.DJSJ
     *
     * @param djsj the value for T_SB_DYSB_DYXL.DJSJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setDjsj(Date djsj) {
        this.djsj = djsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.SBZR
     *
     * @return the value of T_SB_DYSB_DYXL.SBZR
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSbzr() {
        return sbzr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.SBZR
     *
     * @param sbzr the value for T_SB_DYSB_DYXL.SBZR
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSbzr(String sbzr) {
        this.sbzr = sbzr == null ? null : sbzr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.ZCDWMC
     *
     * @return the value of T_SB_DYSB_DYXL.ZCDWMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZcdwmc() {
        return zcdwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.ZCDWMC
     *
     * @param zcdwmc the value for T_SB_DYSB_DYXL.ZCDWMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZcdwmc(String zcdwmc) {
        this.zcdwmc = zcdwmc == null ? null : zcdwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.SSDSMC
     *
     * @return the value of T_SB_DYSB_DYXL.SSDSMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSsdsmc() {
        return ssdsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.SSDSMC
     *
     * @param ssdsmc the value for T_SB_DYSB_DYXL.SSDSMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSsdsmc(String ssdsmc) {
        this.ssdsmc = ssdsmc == null ? null : ssdsmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.WHBZMC
     *
     * @return the value of T_SB_DYSB_DYXL.WHBZMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getWhbzmc() {
        return whbzmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.WHBZMC
     *
     * @param whbzmc the value for T_SB_DYSB_DYXL.WHBZMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setWhbzmc(String whbzmc) {
        this.whbzmc = whbzmc == null ? null : whbzmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.YWDWMC
     *
     * @return the value of T_SB_DYSB_DYXL.YWDWMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getYwdwmc() {
        return ywdwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.YWDWMC
     *
     * @param ywdwmc the value for T_SB_DYSB_DYXL.YWDWMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setYwdwmc(String ywdwmc) {
        this.ywdwmc = ywdwmc == null ? null : ywdwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.SBZRMC
     *
     * @return the value of T_SB_DYSB_DYXL.SBZRMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSbzrmc() {
        return sbzrmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.SBZRMC
     *
     * @param sbzrmc the value for T_SB_DYSB_DYXL.SBZRMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSbzrmc(String sbzrmc) {
        this.sbzrmc = sbzrmc == null ? null : sbzrmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.FBZT
     *
     * @return the value of T_SB_DYSB_DYXL.FBZT
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getFbzt() {
        return fbzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.FBZT
     *
     * @param fbzt the value for T_SB_DYSB_DYXL.FBZT
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setFbzt(String fbzt) {
        this.fbzt = fbzt == null ? null : fbzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.ZYFL
     *
     * @return the value of T_SB_DYSB_DYXL.ZYFL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZyfl() {
        return zyfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.ZYFL
     *
     * @param zyfl the value for T_SB_DYSB_DYXL.ZYFL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZyfl(String zyfl) {
        this.zyfl = zyfl == null ? null : zyfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_DYSB_DYXL.XGHSBMC
     *
     * @return the value of T_SB_DYSB_DYXL.XGHSBMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getXghsbmc() {
        return xghsbmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_DYSB_DYXL.XGHSBMC
     *
     * @param xghsbmc the value for T_SB_DYSB_DYXL.XGHSBMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setXghsbmc(String xghsbmc) {
        this.xghsbmc = xghsbmc == null ? null : xghsbmc.trim();
    }
}