package com.lnsoft.module.pms.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TSbZnycJddz {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.OBJ_ID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String objId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.SBBM
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sbbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.DXMPYXKID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String dxmpyxkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.JGDY
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String jgdy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.YWDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String ywdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.SBMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sbmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.DYDJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String dydj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.TYRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private Date tyrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.SCCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sccj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.CCRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private Date ccrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.YXBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String yxbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.SSDS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String ssds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.WHBZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String whbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.SSZF
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sszf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.YXZT
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String yxzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.ZCXZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zcxz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.ZCDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zcdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.ZCBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zcbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.WBSBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String wbsbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.WBSMS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String wbsms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.SBZJFS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sbzjfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.XH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.ZZS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.EDGL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal edgl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.EDDY
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String eddy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.DZDZZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String dzdzz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.ZDZZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zdzz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.DZCL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String dzcl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.CCBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String ccbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.ZJTYRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private Date zjtyrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.BZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.DJSJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private Date djsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.SBZR
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sbzr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.ZCDWMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zcdwmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.WHBZMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String whbzmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.SBZRMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sbzrmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.SSDSMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String ssdsmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.YWDWMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String ywdwmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.SBPBS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sbpbs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.SFNW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sfnw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.FBZT
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String fbzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.SYHJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String syhj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.ZZGJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zzgj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.EDDZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal eddz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.ERPWBSBM
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String erpwbsbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.ZYFL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zyfl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.XGHSBMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String xghsbmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.SJSBID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sjsbid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_JDDZ.ZHSBLX
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zhsblx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.OBJ_ID
     *
     * @return the value of T_SB_ZNYC_JDDZ.OBJ_ID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getObjId() {
        return objId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.OBJ_ID
     *
     * @param objId the value for T_SB_ZNYC_JDDZ.OBJ_ID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setObjId(String objId) {
        this.objId = objId == null ? null : objId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.SBBM
     *
     * @return the value of T_SB_ZNYC_JDDZ.SBBM
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSbbm() {
        return sbbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.SBBM
     *
     * @param sbbm the value for T_SB_ZNYC_JDDZ.SBBM
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSbbm(String sbbm) {
        this.sbbm = sbbm == null ? null : sbbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.DXMPYXKID
     *
     * @return the value of T_SB_ZNYC_JDDZ.DXMPYXKID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getDxmpyxkid() {
        return dxmpyxkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.DXMPYXKID
     *
     * @param dxmpyxkid the value for T_SB_ZNYC_JDDZ.DXMPYXKID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setDxmpyxkid(String dxmpyxkid) {
        this.dxmpyxkid = dxmpyxkid == null ? null : dxmpyxkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.JGDY
     *
     * @return the value of T_SB_ZNYC_JDDZ.JGDY
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getJgdy() {
        return jgdy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.JGDY
     *
     * @param jgdy the value for T_SB_ZNYC_JDDZ.JGDY
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setJgdy(String jgdy) {
        this.jgdy = jgdy == null ? null : jgdy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.YWDW
     *
     * @return the value of T_SB_ZNYC_JDDZ.YWDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getYwdw() {
        return ywdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.YWDW
     *
     * @param ywdw the value for T_SB_ZNYC_JDDZ.YWDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setYwdw(String ywdw) {
        this.ywdw = ywdw == null ? null : ywdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.SBMC
     *
     * @return the value of T_SB_ZNYC_JDDZ.SBMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSbmc() {
        return sbmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.SBMC
     *
     * @param sbmc the value for T_SB_ZNYC_JDDZ.SBMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSbmc(String sbmc) {
        this.sbmc = sbmc == null ? null : sbmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.DYDJ
     *
     * @return the value of T_SB_ZNYC_JDDZ.DYDJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getDydj() {
        return dydj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.DYDJ
     *
     * @param dydj the value for T_SB_ZNYC_JDDZ.DYDJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setDydj(String dydj) {
        this.dydj = dydj == null ? null : dydj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.TYRQ
     *
     * @return the value of T_SB_ZNYC_JDDZ.TYRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public Date getTyrq() {
        return tyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.TYRQ
     *
     * @param tyrq the value for T_SB_ZNYC_JDDZ.TYRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setTyrq(Date tyrq) {
        this.tyrq = tyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.SCCJ
     *
     * @return the value of T_SB_ZNYC_JDDZ.SCCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSccj() {
        return sccj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.SCCJ
     *
     * @param sccj the value for T_SB_ZNYC_JDDZ.SCCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSccj(String sccj) {
        this.sccj = sccj == null ? null : sccj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.CCRQ
     *
     * @return the value of T_SB_ZNYC_JDDZ.CCRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public Date getCcrq() {
        return ccrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.CCRQ
     *
     * @param ccrq the value for T_SB_ZNYC_JDDZ.CCRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setCcrq(Date ccrq) {
        this.ccrq = ccrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.YXBH
     *
     * @return the value of T_SB_ZNYC_JDDZ.YXBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getYxbh() {
        return yxbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.YXBH
     *
     * @param yxbh the value for T_SB_ZNYC_JDDZ.YXBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setYxbh(String yxbh) {
        this.yxbh = yxbh == null ? null : yxbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.SSDS
     *
     * @return the value of T_SB_ZNYC_JDDZ.SSDS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSsds() {
        return ssds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.SSDS
     *
     * @param ssds the value for T_SB_ZNYC_JDDZ.SSDS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSsds(String ssds) {
        this.ssds = ssds == null ? null : ssds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.WHBZ
     *
     * @return the value of T_SB_ZNYC_JDDZ.WHBZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getWhbz() {
        return whbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.WHBZ
     *
     * @param whbz the value for T_SB_ZNYC_JDDZ.WHBZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setWhbz(String whbz) {
        this.whbz = whbz == null ? null : whbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.SSZF
     *
     * @return the value of T_SB_ZNYC_JDDZ.SSZF
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSszf() {
        return sszf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.SSZF
     *
     * @param sszf the value for T_SB_ZNYC_JDDZ.SSZF
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSszf(String sszf) {
        this.sszf = sszf == null ? null : sszf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.YXZT
     *
     * @return the value of T_SB_ZNYC_JDDZ.YXZT
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getYxzt() {
        return yxzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.YXZT
     *
     * @param yxzt the value for T_SB_ZNYC_JDDZ.YXZT
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setYxzt(String yxzt) {
        this.yxzt = yxzt == null ? null : yxzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.ZCXZ
     *
     * @return the value of T_SB_ZNYC_JDDZ.ZCXZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZcxz() {
        return zcxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.ZCXZ
     *
     * @param zcxz the value for T_SB_ZNYC_JDDZ.ZCXZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZcxz(String zcxz) {
        this.zcxz = zcxz == null ? null : zcxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.ZCDW
     *
     * @return the value of T_SB_ZNYC_JDDZ.ZCDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZcdw() {
        return zcdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.ZCDW
     *
     * @param zcdw the value for T_SB_ZNYC_JDDZ.ZCDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZcdw(String zcdw) {
        this.zcdw = zcdw == null ? null : zcdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.ZCBH
     *
     * @return the value of T_SB_ZNYC_JDDZ.ZCBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZcbh() {
        return zcbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.ZCBH
     *
     * @param zcbh the value for T_SB_ZNYC_JDDZ.ZCBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZcbh(String zcbh) {
        this.zcbh = zcbh == null ? null : zcbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.WBSBH
     *
     * @return the value of T_SB_ZNYC_JDDZ.WBSBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getWbsbh() {
        return wbsbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.WBSBH
     *
     * @param wbsbh the value for T_SB_ZNYC_JDDZ.WBSBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setWbsbh(String wbsbh) {
        this.wbsbh = wbsbh == null ? null : wbsbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.WBSMS
     *
     * @return the value of T_SB_ZNYC_JDDZ.WBSMS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getWbsms() {
        return wbsms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.WBSMS
     *
     * @param wbsms the value for T_SB_ZNYC_JDDZ.WBSMS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setWbsms(String wbsms) {
        this.wbsms = wbsms == null ? null : wbsms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.SBZJFS
     *
     * @return the value of T_SB_ZNYC_JDDZ.SBZJFS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSbzjfs() {
        return sbzjfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.SBZJFS
     *
     * @param sbzjfs the value for T_SB_ZNYC_JDDZ.SBZJFS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSbzjfs(String sbzjfs) {
        this.sbzjfs = sbzjfs == null ? null : sbzjfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.XH
     *
     * @return the value of T_SB_ZNYC_JDDZ.XH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.XH
     *
     * @param xh the value for T_SB_ZNYC_JDDZ.XH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setXh(String xh) {
        this.xh = xh == null ? null : xh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.ZZS
     *
     * @return the value of T_SB_ZNYC_JDDZ.ZZS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZzs() {
        return zzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.ZZS
     *
     * @param zzs the value for T_SB_ZNYC_JDDZ.ZZS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZzs(String zzs) {
        this.zzs = zzs == null ? null : zzs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.EDGL
     *
     * @return the value of T_SB_ZNYC_JDDZ.EDGL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getEdgl() {
        return edgl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.EDGL
     *
     * @param edgl the value for T_SB_ZNYC_JDDZ.EDGL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setEdgl(BigDecimal edgl) {
        this.edgl = edgl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.EDDY
     *
     * @return the value of T_SB_ZNYC_JDDZ.EDDY
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getEddy() {
        return eddy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.EDDY
     *
     * @param eddy the value for T_SB_ZNYC_JDDZ.EDDY
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setEddy(String eddy) {
        this.eddy = eddy == null ? null : eddy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.DZDZZ
     *
     * @return the value of T_SB_ZNYC_JDDZ.DZDZZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getDzdzz() {
        return dzdzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.DZDZZ
     *
     * @param dzdzz the value for T_SB_ZNYC_JDDZ.DZDZZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setDzdzz(String dzdzz) {
        this.dzdzz = dzdzz == null ? null : dzdzz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.ZDZZ
     *
     * @return the value of T_SB_ZNYC_JDDZ.ZDZZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZdzz() {
        return zdzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.ZDZZ
     *
     * @param zdzz the value for T_SB_ZNYC_JDDZ.ZDZZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZdzz(String zdzz) {
        this.zdzz = zdzz == null ? null : zdzz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.DZCL
     *
     * @return the value of T_SB_ZNYC_JDDZ.DZCL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getDzcl() {
        return dzcl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.DZCL
     *
     * @param dzcl the value for T_SB_ZNYC_JDDZ.DZCL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setDzcl(String dzcl) {
        this.dzcl = dzcl == null ? null : dzcl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.CCBH
     *
     * @return the value of T_SB_ZNYC_JDDZ.CCBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getCcbh() {
        return ccbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.CCBH
     *
     * @param ccbh the value for T_SB_ZNYC_JDDZ.CCBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setCcbh(String ccbh) {
        this.ccbh = ccbh == null ? null : ccbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.ZJTYRQ
     *
     * @return the value of T_SB_ZNYC_JDDZ.ZJTYRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public Date getZjtyrq() {
        return zjtyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.ZJTYRQ
     *
     * @param zjtyrq the value for T_SB_ZNYC_JDDZ.ZJTYRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZjtyrq(Date zjtyrq) {
        this.zjtyrq = zjtyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.BZ
     *
     * @return the value of T_SB_ZNYC_JDDZ.BZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.BZ
     *
     * @param bz the value for T_SB_ZNYC_JDDZ.BZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.DJSJ
     *
     * @return the value of T_SB_ZNYC_JDDZ.DJSJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public Date getDjsj() {
        return djsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.DJSJ
     *
     * @param djsj the value for T_SB_ZNYC_JDDZ.DJSJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setDjsj(Date djsj) {
        this.djsj = djsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.SBZR
     *
     * @return the value of T_SB_ZNYC_JDDZ.SBZR
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSbzr() {
        return sbzr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.SBZR
     *
     * @param sbzr the value for T_SB_ZNYC_JDDZ.SBZR
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSbzr(String sbzr) {
        this.sbzr = sbzr == null ? null : sbzr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.ZCDWMC
     *
     * @return the value of T_SB_ZNYC_JDDZ.ZCDWMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZcdwmc() {
        return zcdwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.ZCDWMC
     *
     * @param zcdwmc the value for T_SB_ZNYC_JDDZ.ZCDWMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZcdwmc(String zcdwmc) {
        this.zcdwmc = zcdwmc == null ? null : zcdwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.WHBZMC
     *
     * @return the value of T_SB_ZNYC_JDDZ.WHBZMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getWhbzmc() {
        return whbzmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.WHBZMC
     *
     * @param whbzmc the value for T_SB_ZNYC_JDDZ.WHBZMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setWhbzmc(String whbzmc) {
        this.whbzmc = whbzmc == null ? null : whbzmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.SBZRMC
     *
     * @return the value of T_SB_ZNYC_JDDZ.SBZRMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSbzrmc() {
        return sbzrmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.SBZRMC
     *
     * @param sbzrmc the value for T_SB_ZNYC_JDDZ.SBZRMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSbzrmc(String sbzrmc) {
        this.sbzrmc = sbzrmc == null ? null : sbzrmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.SSDSMC
     *
     * @return the value of T_SB_ZNYC_JDDZ.SSDSMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSsdsmc() {
        return ssdsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.SSDSMC
     *
     * @param ssdsmc the value for T_SB_ZNYC_JDDZ.SSDSMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSsdsmc(String ssdsmc) {
        this.ssdsmc = ssdsmc == null ? null : ssdsmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.YWDWMC
     *
     * @return the value of T_SB_ZNYC_JDDZ.YWDWMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getYwdwmc() {
        return ywdwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.YWDWMC
     *
     * @param ywdwmc the value for T_SB_ZNYC_JDDZ.YWDWMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setYwdwmc(String ywdwmc) {
        this.ywdwmc = ywdwmc == null ? null : ywdwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.SBPBS
     *
     * @return the value of T_SB_ZNYC_JDDZ.SBPBS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSbpbs() {
        return sbpbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.SBPBS
     *
     * @param sbpbs the value for T_SB_ZNYC_JDDZ.SBPBS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSbpbs(String sbpbs) {
        this.sbpbs = sbpbs == null ? null : sbpbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.SFNW
     *
     * @return the value of T_SB_ZNYC_JDDZ.SFNW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSfnw() {
        return sfnw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.SFNW
     *
     * @param sfnw the value for T_SB_ZNYC_JDDZ.SFNW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSfnw(String sfnw) {
        this.sfnw = sfnw == null ? null : sfnw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.FBZT
     *
     * @return the value of T_SB_ZNYC_JDDZ.FBZT
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getFbzt() {
        return fbzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.FBZT
     *
     * @param fbzt the value for T_SB_ZNYC_JDDZ.FBZT
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setFbzt(String fbzt) {
        this.fbzt = fbzt == null ? null : fbzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.SYHJ
     *
     * @return the value of T_SB_ZNYC_JDDZ.SYHJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSyhj() {
        return syhj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.SYHJ
     *
     * @param syhj the value for T_SB_ZNYC_JDDZ.SYHJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSyhj(String syhj) {
        this.syhj = syhj == null ? null : syhj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.ZZGJ
     *
     * @return the value of T_SB_ZNYC_JDDZ.ZZGJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZzgj() {
        return zzgj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.ZZGJ
     *
     * @param zzgj the value for T_SB_ZNYC_JDDZ.ZZGJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZzgj(String zzgj) {
        this.zzgj = zzgj == null ? null : zzgj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.EDDZ
     *
     * @return the value of T_SB_ZNYC_JDDZ.EDDZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getEddz() {
        return eddz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.EDDZ
     *
     * @param eddz the value for T_SB_ZNYC_JDDZ.EDDZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setEddz(BigDecimal eddz) {
        this.eddz = eddz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.ERPWBSBM
     *
     * @return the value of T_SB_ZNYC_JDDZ.ERPWBSBM
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getErpwbsbm() {
        return erpwbsbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.ERPWBSBM
     *
     * @param erpwbsbm the value for T_SB_ZNYC_JDDZ.ERPWBSBM
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setErpwbsbm(String erpwbsbm) {
        this.erpwbsbm = erpwbsbm == null ? null : erpwbsbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.ZYFL
     *
     * @return the value of T_SB_ZNYC_JDDZ.ZYFL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZyfl() {
        return zyfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.ZYFL
     *
     * @param zyfl the value for T_SB_ZNYC_JDDZ.ZYFL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZyfl(String zyfl) {
        this.zyfl = zyfl == null ? null : zyfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.XGHSBMC
     *
     * @return the value of T_SB_ZNYC_JDDZ.XGHSBMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getXghsbmc() {
        return xghsbmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.XGHSBMC
     *
     * @param xghsbmc the value for T_SB_ZNYC_JDDZ.XGHSBMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setXghsbmc(String xghsbmc) {
        this.xghsbmc = xghsbmc == null ? null : xghsbmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.SJSBID
     *
     * @return the value of T_SB_ZNYC_JDDZ.SJSBID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSjsbid() {
        return sjsbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.SJSBID
     *
     * @param sjsbid the value for T_SB_ZNYC_JDDZ.SJSBID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSjsbid(String sjsbid) {
        this.sjsbid = sjsbid == null ? null : sjsbid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_JDDZ.ZHSBLX
     *
     * @return the value of T_SB_ZNYC_JDDZ.ZHSBLX
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZhsblx() {
        return zhsblx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_JDDZ.ZHSBLX
     *
     * @param zhsblx the value for T_SB_ZNYC_JDDZ.ZHSBLX
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZhsblx(String zhsblx) {
        this.zhsblx = zhsblx == null ? null : zhsblx.trim();
    }
}