package com.lnsoft.module.pms.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TSbZwycXlblq {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.OBJ_ID
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String objId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.SSGT
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String ssgt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.SBBM
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String sbbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.SBMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String sbmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.YWDW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String ywdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.YXBH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String yxbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.SSXL
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String ssxl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.SSDS
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String ssds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.ZYCD
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String zycd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.WHBZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String whbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.YXZT
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String yxzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.SFDW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String sfdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.XH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.SCCJ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String sccj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.TYRQ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private Date tyrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.CCRQ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private Date ccrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.CCBH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String ccbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.EDDY
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String eddy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.GPFDDY
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private BigDecimal gpfddy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.CXYXDY
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private BigDecimal cxyxdy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.BCFDDL
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private BigDecimal bcfddl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.LJCJDLXCY
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private BigDecimal ljcjdlxcy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.ZLCK1ADY
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private BigDecimal zlck1ady;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.JSQDZCS
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private BigDecimal jsqdzcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.JSQXH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String jsqxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.JSQSCCJ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String jsqsccj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.YWXHCQX
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String ywxhcqx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.JDDZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private BigDecimal jddz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.ZCXZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String zcxz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.ZCDW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String zcdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.ZCBH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String zcbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.BZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.AZXBJB
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String azxbjb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.DJSJ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private Date djsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.SBZR
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String sbzr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.SBZRMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String sbzrmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.YWDWMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String ywdwmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.SSDSMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String ssdsmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.WHBZMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String whbzmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.ZCDWMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String zcdwmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.SFNW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String sfnw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.SSFDXL
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String ssfdxl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.SBPBS
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String sbpbs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.DYDJ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String dydj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.ZXMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String zxmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.FBZT
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String fbzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.AZWZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String azwz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.SL
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String sl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.ZYFL
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String zyfl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.XGHSBMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String xghsbmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.SSDKX
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String ssdkx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZWYC_XLBLQ.SSKXXD
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String sskxxd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.OBJ_ID
     *
     * @return the value of T_SB_ZWYC_XLBLQ.OBJ_ID
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getObjId() {
        return objId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.OBJ_ID
     *
     * @param objId the value for T_SB_ZWYC_XLBLQ.OBJ_ID
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setObjId(String objId) {
        this.objId = objId == null ? null : objId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.SSGT
     *
     * @return the value of T_SB_ZWYC_XLBLQ.SSGT
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSsgt() {
        return ssgt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.SSGT
     *
     * @param ssgt the value for T_SB_ZWYC_XLBLQ.SSGT
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSsgt(String ssgt) {
        this.ssgt = ssgt == null ? null : ssgt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.SBBM
     *
     * @return the value of T_SB_ZWYC_XLBLQ.SBBM
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSbbm() {
        return sbbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.SBBM
     *
     * @param sbbm the value for T_SB_ZWYC_XLBLQ.SBBM
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSbbm(String sbbm) {
        this.sbbm = sbbm == null ? null : sbbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.SBMC
     *
     * @return the value of T_SB_ZWYC_XLBLQ.SBMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSbmc() {
        return sbmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.SBMC
     *
     * @param sbmc the value for T_SB_ZWYC_XLBLQ.SBMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSbmc(String sbmc) {
        this.sbmc = sbmc == null ? null : sbmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.YWDW
     *
     * @return the value of T_SB_ZWYC_XLBLQ.YWDW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getYwdw() {
        return ywdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.YWDW
     *
     * @param ywdw the value for T_SB_ZWYC_XLBLQ.YWDW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setYwdw(String ywdw) {
        this.ywdw = ywdw == null ? null : ywdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.YXBH
     *
     * @return the value of T_SB_ZWYC_XLBLQ.YXBH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getYxbh() {
        return yxbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.YXBH
     *
     * @param yxbh the value for T_SB_ZWYC_XLBLQ.YXBH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setYxbh(String yxbh) {
        this.yxbh = yxbh == null ? null : yxbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.SSXL
     *
     * @return the value of T_SB_ZWYC_XLBLQ.SSXL
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSsxl() {
        return ssxl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.SSXL
     *
     * @param ssxl the value for T_SB_ZWYC_XLBLQ.SSXL
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSsxl(String ssxl) {
        this.ssxl = ssxl == null ? null : ssxl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.SSDS
     *
     * @return the value of T_SB_ZWYC_XLBLQ.SSDS
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSsds() {
        return ssds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.SSDS
     *
     * @param ssds the value for T_SB_ZWYC_XLBLQ.SSDS
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSsds(String ssds) {
        this.ssds = ssds == null ? null : ssds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.ZYCD
     *
     * @return the value of T_SB_ZWYC_XLBLQ.ZYCD
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getZycd() {
        return zycd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.ZYCD
     *
     * @param zycd the value for T_SB_ZWYC_XLBLQ.ZYCD
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setZycd(String zycd) {
        this.zycd = zycd == null ? null : zycd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.WHBZ
     *
     * @return the value of T_SB_ZWYC_XLBLQ.WHBZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getWhbz() {
        return whbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.WHBZ
     *
     * @param whbz the value for T_SB_ZWYC_XLBLQ.WHBZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setWhbz(String whbz) {
        this.whbz = whbz == null ? null : whbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.YXZT
     *
     * @return the value of T_SB_ZWYC_XLBLQ.YXZT
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getYxzt() {
        return yxzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.YXZT
     *
     * @param yxzt the value for T_SB_ZWYC_XLBLQ.YXZT
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setYxzt(String yxzt) {
        this.yxzt = yxzt == null ? null : yxzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.SFDW
     *
     * @return the value of T_SB_ZWYC_XLBLQ.SFDW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSfdw() {
        return sfdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.SFDW
     *
     * @param sfdw the value for T_SB_ZWYC_XLBLQ.SFDW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSfdw(String sfdw) {
        this.sfdw = sfdw == null ? null : sfdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.XH
     *
     * @return the value of T_SB_ZWYC_XLBLQ.XH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.XH
     *
     * @param xh the value for T_SB_ZWYC_XLBLQ.XH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setXh(String xh) {
        this.xh = xh == null ? null : xh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.SCCJ
     *
     * @return the value of T_SB_ZWYC_XLBLQ.SCCJ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSccj() {
        return sccj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.SCCJ
     *
     * @param sccj the value for T_SB_ZWYC_XLBLQ.SCCJ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSccj(String sccj) {
        this.sccj = sccj == null ? null : sccj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.TYRQ
     *
     * @return the value of T_SB_ZWYC_XLBLQ.TYRQ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public Date getTyrq() {
        return tyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.TYRQ
     *
     * @param tyrq the value for T_SB_ZWYC_XLBLQ.TYRQ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setTyrq(Date tyrq) {
        this.tyrq = tyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.CCRQ
     *
     * @return the value of T_SB_ZWYC_XLBLQ.CCRQ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public Date getCcrq() {
        return ccrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.CCRQ
     *
     * @param ccrq the value for T_SB_ZWYC_XLBLQ.CCRQ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setCcrq(Date ccrq) {
        this.ccrq = ccrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.CCBH
     *
     * @return the value of T_SB_ZWYC_XLBLQ.CCBH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getCcbh() {
        return ccbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.CCBH
     *
     * @param ccbh the value for T_SB_ZWYC_XLBLQ.CCBH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setCcbh(String ccbh) {
        this.ccbh = ccbh == null ? null : ccbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.EDDY
     *
     * @return the value of T_SB_ZWYC_XLBLQ.EDDY
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getEddy() {
        return eddy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.EDDY
     *
     * @param eddy the value for T_SB_ZWYC_XLBLQ.EDDY
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setEddy(String eddy) {
        this.eddy = eddy == null ? null : eddy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.GPFDDY
     *
     * @return the value of T_SB_ZWYC_XLBLQ.GPFDDY
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public BigDecimal getGpfddy() {
        return gpfddy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.GPFDDY
     *
     * @param gpfddy the value for T_SB_ZWYC_XLBLQ.GPFDDY
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setGpfddy(BigDecimal gpfddy) {
        this.gpfddy = gpfddy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.CXYXDY
     *
     * @return the value of T_SB_ZWYC_XLBLQ.CXYXDY
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public BigDecimal getCxyxdy() {
        return cxyxdy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.CXYXDY
     *
     * @param cxyxdy the value for T_SB_ZWYC_XLBLQ.CXYXDY
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setCxyxdy(BigDecimal cxyxdy) {
        this.cxyxdy = cxyxdy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.BCFDDL
     *
     * @return the value of T_SB_ZWYC_XLBLQ.BCFDDL
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public BigDecimal getBcfddl() {
        return bcfddl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.BCFDDL
     *
     * @param bcfddl the value for T_SB_ZWYC_XLBLQ.BCFDDL
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setBcfddl(BigDecimal bcfddl) {
        this.bcfddl = bcfddl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.LJCJDLXCY
     *
     * @return the value of T_SB_ZWYC_XLBLQ.LJCJDLXCY
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public BigDecimal getLjcjdlxcy() {
        return ljcjdlxcy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.LJCJDLXCY
     *
     * @param ljcjdlxcy the value for T_SB_ZWYC_XLBLQ.LJCJDLXCY
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setLjcjdlxcy(BigDecimal ljcjdlxcy) {
        this.ljcjdlxcy = ljcjdlxcy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.ZLCK1ADY
     *
     * @return the value of T_SB_ZWYC_XLBLQ.ZLCK1ADY
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public BigDecimal getZlck1ady() {
        return zlck1ady;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.ZLCK1ADY
     *
     * @param zlck1ady the value for T_SB_ZWYC_XLBLQ.ZLCK1ADY
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setZlck1ady(BigDecimal zlck1ady) {
        this.zlck1ady = zlck1ady;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.JSQDZCS
     *
     * @return the value of T_SB_ZWYC_XLBLQ.JSQDZCS
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public BigDecimal getJsqdzcs() {
        return jsqdzcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.JSQDZCS
     *
     * @param jsqdzcs the value for T_SB_ZWYC_XLBLQ.JSQDZCS
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setJsqdzcs(BigDecimal jsqdzcs) {
        this.jsqdzcs = jsqdzcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.JSQXH
     *
     * @return the value of T_SB_ZWYC_XLBLQ.JSQXH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getJsqxh() {
        return jsqxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.JSQXH
     *
     * @param jsqxh the value for T_SB_ZWYC_XLBLQ.JSQXH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setJsqxh(String jsqxh) {
        this.jsqxh = jsqxh == null ? null : jsqxh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.JSQSCCJ
     *
     * @return the value of T_SB_ZWYC_XLBLQ.JSQSCCJ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getJsqsccj() {
        return jsqsccj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.JSQSCCJ
     *
     * @param jsqsccj the value for T_SB_ZWYC_XLBLQ.JSQSCCJ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setJsqsccj(String jsqsccj) {
        this.jsqsccj = jsqsccj == null ? null : jsqsccj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.YWXHCQX
     *
     * @return the value of T_SB_ZWYC_XLBLQ.YWXHCQX
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getYwxhcqx() {
        return ywxhcqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.YWXHCQX
     *
     * @param ywxhcqx the value for T_SB_ZWYC_XLBLQ.YWXHCQX
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setYwxhcqx(String ywxhcqx) {
        this.ywxhcqx = ywxhcqx == null ? null : ywxhcqx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.JDDZ
     *
     * @return the value of T_SB_ZWYC_XLBLQ.JDDZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public BigDecimal getJddz() {
        return jddz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.JDDZ
     *
     * @param jddz the value for T_SB_ZWYC_XLBLQ.JDDZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setJddz(BigDecimal jddz) {
        this.jddz = jddz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.ZCXZ
     *
     * @return the value of T_SB_ZWYC_XLBLQ.ZCXZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getZcxz() {
        return zcxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.ZCXZ
     *
     * @param zcxz the value for T_SB_ZWYC_XLBLQ.ZCXZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setZcxz(String zcxz) {
        this.zcxz = zcxz == null ? null : zcxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.ZCDW
     *
     * @return the value of T_SB_ZWYC_XLBLQ.ZCDW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getZcdw() {
        return zcdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.ZCDW
     *
     * @param zcdw the value for T_SB_ZWYC_XLBLQ.ZCDW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setZcdw(String zcdw) {
        this.zcdw = zcdw == null ? null : zcdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.ZCBH
     *
     * @return the value of T_SB_ZWYC_XLBLQ.ZCBH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getZcbh() {
        return zcbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.ZCBH
     *
     * @param zcbh the value for T_SB_ZWYC_XLBLQ.ZCBH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setZcbh(String zcbh) {
        this.zcbh = zcbh == null ? null : zcbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.BZ
     *
     * @return the value of T_SB_ZWYC_XLBLQ.BZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.BZ
     *
     * @param bz the value for T_SB_ZWYC_XLBLQ.BZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.AZXBJB
     *
     * @return the value of T_SB_ZWYC_XLBLQ.AZXBJB
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getAzxbjb() {
        return azxbjb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.AZXBJB
     *
     * @param azxbjb the value for T_SB_ZWYC_XLBLQ.AZXBJB
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setAzxbjb(String azxbjb) {
        this.azxbjb = azxbjb == null ? null : azxbjb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.DJSJ
     *
     * @return the value of T_SB_ZWYC_XLBLQ.DJSJ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public Date getDjsj() {
        return djsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.DJSJ
     *
     * @param djsj the value for T_SB_ZWYC_XLBLQ.DJSJ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setDjsj(Date djsj) {
        this.djsj = djsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.SBZR
     *
     * @return the value of T_SB_ZWYC_XLBLQ.SBZR
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSbzr() {
        return sbzr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.SBZR
     *
     * @param sbzr the value for T_SB_ZWYC_XLBLQ.SBZR
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSbzr(String sbzr) {
        this.sbzr = sbzr == null ? null : sbzr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.SBZRMC
     *
     * @return the value of T_SB_ZWYC_XLBLQ.SBZRMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSbzrmc() {
        return sbzrmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.SBZRMC
     *
     * @param sbzrmc the value for T_SB_ZWYC_XLBLQ.SBZRMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSbzrmc(String sbzrmc) {
        this.sbzrmc = sbzrmc == null ? null : sbzrmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.YWDWMC
     *
     * @return the value of T_SB_ZWYC_XLBLQ.YWDWMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getYwdwmc() {
        return ywdwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.YWDWMC
     *
     * @param ywdwmc the value for T_SB_ZWYC_XLBLQ.YWDWMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setYwdwmc(String ywdwmc) {
        this.ywdwmc = ywdwmc == null ? null : ywdwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.SSDSMC
     *
     * @return the value of T_SB_ZWYC_XLBLQ.SSDSMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSsdsmc() {
        return ssdsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.SSDSMC
     *
     * @param ssdsmc the value for T_SB_ZWYC_XLBLQ.SSDSMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSsdsmc(String ssdsmc) {
        this.ssdsmc = ssdsmc == null ? null : ssdsmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.WHBZMC
     *
     * @return the value of T_SB_ZWYC_XLBLQ.WHBZMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getWhbzmc() {
        return whbzmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.WHBZMC
     *
     * @param whbzmc the value for T_SB_ZWYC_XLBLQ.WHBZMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setWhbzmc(String whbzmc) {
        this.whbzmc = whbzmc == null ? null : whbzmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.ZCDWMC
     *
     * @return the value of T_SB_ZWYC_XLBLQ.ZCDWMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getZcdwmc() {
        return zcdwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.ZCDWMC
     *
     * @param zcdwmc the value for T_SB_ZWYC_XLBLQ.ZCDWMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setZcdwmc(String zcdwmc) {
        this.zcdwmc = zcdwmc == null ? null : zcdwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.SFNW
     *
     * @return the value of T_SB_ZWYC_XLBLQ.SFNW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSfnw() {
        return sfnw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.SFNW
     *
     * @param sfnw the value for T_SB_ZWYC_XLBLQ.SFNW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSfnw(String sfnw) {
        this.sfnw = sfnw == null ? null : sfnw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.SSFDXL
     *
     * @return the value of T_SB_ZWYC_XLBLQ.SSFDXL
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSsfdxl() {
        return ssfdxl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.SSFDXL
     *
     * @param ssfdxl the value for T_SB_ZWYC_XLBLQ.SSFDXL
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSsfdxl(String ssfdxl) {
        this.ssfdxl = ssfdxl == null ? null : ssfdxl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.SBPBS
     *
     * @return the value of T_SB_ZWYC_XLBLQ.SBPBS
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSbpbs() {
        return sbpbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.SBPBS
     *
     * @param sbpbs the value for T_SB_ZWYC_XLBLQ.SBPBS
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSbpbs(String sbpbs) {
        this.sbpbs = sbpbs == null ? null : sbpbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.DYDJ
     *
     * @return the value of T_SB_ZWYC_XLBLQ.DYDJ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getDydj() {
        return dydj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.DYDJ
     *
     * @param dydj the value for T_SB_ZWYC_XLBLQ.DYDJ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setDydj(String dydj) {
        this.dydj = dydj == null ? null : dydj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.ZXMC
     *
     * @return the value of T_SB_ZWYC_XLBLQ.ZXMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getZxmc() {
        return zxmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.ZXMC
     *
     * @param zxmc the value for T_SB_ZWYC_XLBLQ.ZXMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setZxmc(String zxmc) {
        this.zxmc = zxmc == null ? null : zxmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.FBZT
     *
     * @return the value of T_SB_ZWYC_XLBLQ.FBZT
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getFbzt() {
        return fbzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.FBZT
     *
     * @param fbzt the value for T_SB_ZWYC_XLBLQ.FBZT
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setFbzt(String fbzt) {
        this.fbzt = fbzt == null ? null : fbzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.AZWZ
     *
     * @return the value of T_SB_ZWYC_XLBLQ.AZWZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getAzwz() {
        return azwz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.AZWZ
     *
     * @param azwz the value for T_SB_ZWYC_XLBLQ.AZWZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setAzwz(String azwz) {
        this.azwz = azwz == null ? null : azwz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.SL
     *
     * @return the value of T_SB_ZWYC_XLBLQ.SL
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSl() {
        return sl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.SL
     *
     * @param sl the value for T_SB_ZWYC_XLBLQ.SL
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSl(String sl) {
        this.sl = sl == null ? null : sl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.ZYFL
     *
     * @return the value of T_SB_ZWYC_XLBLQ.ZYFL
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getZyfl() {
        return zyfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.ZYFL
     *
     * @param zyfl the value for T_SB_ZWYC_XLBLQ.ZYFL
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setZyfl(String zyfl) {
        this.zyfl = zyfl == null ? null : zyfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.XGHSBMC
     *
     * @return the value of T_SB_ZWYC_XLBLQ.XGHSBMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getXghsbmc() {
        return xghsbmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.XGHSBMC
     *
     * @param xghsbmc the value for T_SB_ZWYC_XLBLQ.XGHSBMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setXghsbmc(String xghsbmc) {
        this.xghsbmc = xghsbmc == null ? null : xghsbmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.SSDKX
     *
     * @return the value of T_SB_ZWYC_XLBLQ.SSDKX
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSsdkx() {
        return ssdkx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.SSDKX
     *
     * @param ssdkx the value for T_SB_ZWYC_XLBLQ.SSDKX
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSsdkx(String ssdkx) {
        this.ssdkx = ssdkx == null ? null : ssdkx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZWYC_XLBLQ.SSKXXD
     *
     * @return the value of T_SB_ZWYC_XLBLQ.SSKXXD
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSskxxd() {
        return sskxxd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZWYC_XLBLQ.SSKXXD
     *
     * @param sskxxd the value for T_SB_ZWYC_XLBLQ.SSKXXD
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSskxxd(String sskxxd) {
        this.sskxxd = sskxxd == null ? null : sskxxd.trim();
    }
}