package com.lnsoft.module.pms.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TSbZnycDyhgq {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.OBJ_ID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String objId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.SJSBID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sjsbid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.DXMPYXKID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String dxmpyxkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.SBMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sbmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.SBBM
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sbbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.JGDY
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String jgdy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.XS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String xs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.XB
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String xb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.EDDY
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String eddy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.EDPL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal edpl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.SCCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sccj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.CCBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String ccbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.CPDH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String cpdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.ZZGJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zzgj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.CCRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private Date ccrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.YXBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String yxbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.ZJTYRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private Date zjtyrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.YXZT
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String yxzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.SYHJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String syhj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.ZCBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zcbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.WBSBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String wbsbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.WBSMS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String wbsms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.SBZJFS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sbzjfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.XH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.ZHSBLX
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zhsblx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.JYJZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String jyjz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.WJYXS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String wjyxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.JGXS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String jgxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.YWDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String ywdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.TXJG
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String txjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.SFQJY
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sfqjy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.EDDYB
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String eddyb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.ECRZZSL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private Integer ecrzzsl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.PDBJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal pdbj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.ZEDDRL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal zeddrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.DRQJS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private Integer drqjs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.SJDRL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal sjdrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.ZJDRL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal zjdrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.XJC1DRL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal xjc1drl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.XJC2DRL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal xjc2drl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.SF6QTEDYL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal sf6qtedyl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.SF6QTBJYL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal sf6qtbjyl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.MFJG
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String mfjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.JYSP
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String jysp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.ECRZSLCL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private Integer ecrzslcl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.ECRZSLBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private Integer ecrzslbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.GD
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal gd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.SSZF
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sszf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.EDKLZJDY
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal edklzjdy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.SCFYB
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String scfyb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.SJDRQBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sjdrqbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.SJDRQXS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sjdrqxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.ZJDRQBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zjdrqbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.ZJDRQXS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zjdrqxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.XJC1DRQBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String xjc1drqbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.XJC1DRQXS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String xjc1drqxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.XJC2DRQBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String xjc2drqbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.ZCXZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zcxz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.XJC2DRQXS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String xjc2drqxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.YCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String ycj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.YZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal yz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.SF6QTZL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal sf6qtzl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.ZQJCL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zqjcl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.ZQJBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zqjbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.EDSCRLCL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal edscrlcl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.EDSCRLBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal edscrlbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.TYRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private Date tyrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.ZCDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zcdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.DYDJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String dydj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.ZHDQKGGMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zhdqkggmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.ECXHSCXS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String ecxhscxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.LX
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String lx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.YH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String yh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.ZZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal zz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.SSDS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String ssds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.WHBZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String whbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.SFDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sfdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.EDECRL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal edecrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.ZQDJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zqdj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.BZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.DJSJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private Date djsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.SBZR
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sbzr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.YWDWMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String ywdwmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.SSDSMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String ssdsmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.SBZRMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sbzrmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.ZCDWMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zcdwmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.WHBZMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String whbzmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.SFNW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sfnw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.DQTZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String dqtz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.SBPBS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sbpbs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.CLBB
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String clbb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.BHBB
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String bhbb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.FBZT
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String fbzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.ERPWBSBM
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String erpwbsbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.ZYFL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zyfl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.XGHSBMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String xghsbmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_DYHGQ.SFYC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sfyc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.OBJ_ID
     *
     * @return the value of T_SB_ZNYC_DYHGQ.OBJ_ID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getObjId() {
        return objId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.OBJ_ID
     *
     * @param objId the value for T_SB_ZNYC_DYHGQ.OBJ_ID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setObjId(String objId) {
        this.objId = objId == null ? null : objId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.SJSBID
     *
     * @return the value of T_SB_ZNYC_DYHGQ.SJSBID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSjsbid() {
        return sjsbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.SJSBID
     *
     * @param sjsbid the value for T_SB_ZNYC_DYHGQ.SJSBID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSjsbid(String sjsbid) {
        this.sjsbid = sjsbid == null ? null : sjsbid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.DXMPYXKID
     *
     * @return the value of T_SB_ZNYC_DYHGQ.DXMPYXKID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getDxmpyxkid() {
        return dxmpyxkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.DXMPYXKID
     *
     * @param dxmpyxkid the value for T_SB_ZNYC_DYHGQ.DXMPYXKID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setDxmpyxkid(String dxmpyxkid) {
        this.dxmpyxkid = dxmpyxkid == null ? null : dxmpyxkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.SBMC
     *
     * @return the value of T_SB_ZNYC_DYHGQ.SBMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSbmc() {
        return sbmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.SBMC
     *
     * @param sbmc the value for T_SB_ZNYC_DYHGQ.SBMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSbmc(String sbmc) {
        this.sbmc = sbmc == null ? null : sbmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.SBBM
     *
     * @return the value of T_SB_ZNYC_DYHGQ.SBBM
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSbbm() {
        return sbbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.SBBM
     *
     * @param sbbm the value for T_SB_ZNYC_DYHGQ.SBBM
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSbbm(String sbbm) {
        this.sbbm = sbbm == null ? null : sbbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.JGDY
     *
     * @return the value of T_SB_ZNYC_DYHGQ.JGDY
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getJgdy() {
        return jgdy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.JGDY
     *
     * @param jgdy the value for T_SB_ZNYC_DYHGQ.JGDY
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setJgdy(String jgdy) {
        this.jgdy = jgdy == null ? null : jgdy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.XS
     *
     * @return the value of T_SB_ZNYC_DYHGQ.XS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getXs() {
        return xs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.XS
     *
     * @param xs the value for T_SB_ZNYC_DYHGQ.XS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setXs(String xs) {
        this.xs = xs == null ? null : xs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.XB
     *
     * @return the value of T_SB_ZNYC_DYHGQ.XB
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.XB
     *
     * @param xb the value for T_SB_ZNYC_DYHGQ.XB
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.EDDY
     *
     * @return the value of T_SB_ZNYC_DYHGQ.EDDY
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getEddy() {
        return eddy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.EDDY
     *
     * @param eddy the value for T_SB_ZNYC_DYHGQ.EDDY
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setEddy(String eddy) {
        this.eddy = eddy == null ? null : eddy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.EDPL
     *
     * @return the value of T_SB_ZNYC_DYHGQ.EDPL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getEdpl() {
        return edpl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.EDPL
     *
     * @param edpl the value for T_SB_ZNYC_DYHGQ.EDPL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setEdpl(BigDecimal edpl) {
        this.edpl = edpl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.SCCJ
     *
     * @return the value of T_SB_ZNYC_DYHGQ.SCCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSccj() {
        return sccj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.SCCJ
     *
     * @param sccj the value for T_SB_ZNYC_DYHGQ.SCCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSccj(String sccj) {
        this.sccj = sccj == null ? null : sccj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.CCBH
     *
     * @return the value of T_SB_ZNYC_DYHGQ.CCBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getCcbh() {
        return ccbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.CCBH
     *
     * @param ccbh the value for T_SB_ZNYC_DYHGQ.CCBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setCcbh(String ccbh) {
        this.ccbh = ccbh == null ? null : ccbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.CPDH
     *
     * @return the value of T_SB_ZNYC_DYHGQ.CPDH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getCpdh() {
        return cpdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.CPDH
     *
     * @param cpdh the value for T_SB_ZNYC_DYHGQ.CPDH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setCpdh(String cpdh) {
        this.cpdh = cpdh == null ? null : cpdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.ZZGJ
     *
     * @return the value of T_SB_ZNYC_DYHGQ.ZZGJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZzgj() {
        return zzgj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.ZZGJ
     *
     * @param zzgj the value for T_SB_ZNYC_DYHGQ.ZZGJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZzgj(String zzgj) {
        this.zzgj = zzgj == null ? null : zzgj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.CCRQ
     *
     * @return the value of T_SB_ZNYC_DYHGQ.CCRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public Date getCcrq() {
        return ccrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.CCRQ
     *
     * @param ccrq the value for T_SB_ZNYC_DYHGQ.CCRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setCcrq(Date ccrq) {
        this.ccrq = ccrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.YXBH
     *
     * @return the value of T_SB_ZNYC_DYHGQ.YXBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getYxbh() {
        return yxbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.YXBH
     *
     * @param yxbh the value for T_SB_ZNYC_DYHGQ.YXBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setYxbh(String yxbh) {
        this.yxbh = yxbh == null ? null : yxbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.ZJTYRQ
     *
     * @return the value of T_SB_ZNYC_DYHGQ.ZJTYRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public Date getZjtyrq() {
        return zjtyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.ZJTYRQ
     *
     * @param zjtyrq the value for T_SB_ZNYC_DYHGQ.ZJTYRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZjtyrq(Date zjtyrq) {
        this.zjtyrq = zjtyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.YXZT
     *
     * @return the value of T_SB_ZNYC_DYHGQ.YXZT
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getYxzt() {
        return yxzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.YXZT
     *
     * @param yxzt the value for T_SB_ZNYC_DYHGQ.YXZT
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setYxzt(String yxzt) {
        this.yxzt = yxzt == null ? null : yxzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.SYHJ
     *
     * @return the value of T_SB_ZNYC_DYHGQ.SYHJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSyhj() {
        return syhj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.SYHJ
     *
     * @param syhj the value for T_SB_ZNYC_DYHGQ.SYHJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSyhj(String syhj) {
        this.syhj = syhj == null ? null : syhj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.ZCBH
     *
     * @return the value of T_SB_ZNYC_DYHGQ.ZCBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZcbh() {
        return zcbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.ZCBH
     *
     * @param zcbh the value for T_SB_ZNYC_DYHGQ.ZCBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZcbh(String zcbh) {
        this.zcbh = zcbh == null ? null : zcbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.WBSBH
     *
     * @return the value of T_SB_ZNYC_DYHGQ.WBSBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getWbsbh() {
        return wbsbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.WBSBH
     *
     * @param wbsbh the value for T_SB_ZNYC_DYHGQ.WBSBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setWbsbh(String wbsbh) {
        this.wbsbh = wbsbh == null ? null : wbsbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.WBSMS
     *
     * @return the value of T_SB_ZNYC_DYHGQ.WBSMS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getWbsms() {
        return wbsms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.WBSMS
     *
     * @param wbsms the value for T_SB_ZNYC_DYHGQ.WBSMS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setWbsms(String wbsms) {
        this.wbsms = wbsms == null ? null : wbsms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.SBZJFS
     *
     * @return the value of T_SB_ZNYC_DYHGQ.SBZJFS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSbzjfs() {
        return sbzjfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.SBZJFS
     *
     * @param sbzjfs the value for T_SB_ZNYC_DYHGQ.SBZJFS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSbzjfs(String sbzjfs) {
        this.sbzjfs = sbzjfs == null ? null : sbzjfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.XH
     *
     * @return the value of T_SB_ZNYC_DYHGQ.XH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.XH
     *
     * @param xh the value for T_SB_ZNYC_DYHGQ.XH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setXh(String xh) {
        this.xh = xh == null ? null : xh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.ZHSBLX
     *
     * @return the value of T_SB_ZNYC_DYHGQ.ZHSBLX
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZhsblx() {
        return zhsblx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.ZHSBLX
     *
     * @param zhsblx the value for T_SB_ZNYC_DYHGQ.ZHSBLX
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZhsblx(String zhsblx) {
        this.zhsblx = zhsblx == null ? null : zhsblx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.JYJZ
     *
     * @return the value of T_SB_ZNYC_DYHGQ.JYJZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getJyjz() {
        return jyjz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.JYJZ
     *
     * @param jyjz the value for T_SB_ZNYC_DYHGQ.JYJZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setJyjz(String jyjz) {
        this.jyjz = jyjz == null ? null : jyjz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.WJYXS
     *
     * @return the value of T_SB_ZNYC_DYHGQ.WJYXS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getWjyxs() {
        return wjyxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.WJYXS
     *
     * @param wjyxs the value for T_SB_ZNYC_DYHGQ.WJYXS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setWjyxs(String wjyxs) {
        this.wjyxs = wjyxs == null ? null : wjyxs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.JGXS
     *
     * @return the value of T_SB_ZNYC_DYHGQ.JGXS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getJgxs() {
        return jgxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.JGXS
     *
     * @param jgxs the value for T_SB_ZNYC_DYHGQ.JGXS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setJgxs(String jgxs) {
        this.jgxs = jgxs == null ? null : jgxs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.YWDW
     *
     * @return the value of T_SB_ZNYC_DYHGQ.YWDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getYwdw() {
        return ywdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.YWDW
     *
     * @param ywdw the value for T_SB_ZNYC_DYHGQ.YWDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setYwdw(String ywdw) {
        this.ywdw = ywdw == null ? null : ywdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.TXJG
     *
     * @return the value of T_SB_ZNYC_DYHGQ.TXJG
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getTxjg() {
        return txjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.TXJG
     *
     * @param txjg the value for T_SB_ZNYC_DYHGQ.TXJG
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setTxjg(String txjg) {
        this.txjg = txjg == null ? null : txjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.SFQJY
     *
     * @return the value of T_SB_ZNYC_DYHGQ.SFQJY
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSfqjy() {
        return sfqjy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.SFQJY
     *
     * @param sfqjy the value for T_SB_ZNYC_DYHGQ.SFQJY
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSfqjy(String sfqjy) {
        this.sfqjy = sfqjy == null ? null : sfqjy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.EDDYB
     *
     * @return the value of T_SB_ZNYC_DYHGQ.EDDYB
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getEddyb() {
        return eddyb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.EDDYB
     *
     * @param eddyb the value for T_SB_ZNYC_DYHGQ.EDDYB
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setEddyb(String eddyb) {
        this.eddyb = eddyb == null ? null : eddyb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.ECRZZSL
     *
     * @return the value of T_SB_ZNYC_DYHGQ.ECRZZSL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public Integer getEcrzzsl() {
        return ecrzzsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.ECRZZSL
     *
     * @param ecrzzsl the value for T_SB_ZNYC_DYHGQ.ECRZZSL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setEcrzzsl(Integer ecrzzsl) {
        this.ecrzzsl = ecrzzsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.PDBJ
     *
     * @return the value of T_SB_ZNYC_DYHGQ.PDBJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getPdbj() {
        return pdbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.PDBJ
     *
     * @param pdbj the value for T_SB_ZNYC_DYHGQ.PDBJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setPdbj(BigDecimal pdbj) {
        this.pdbj = pdbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.ZEDDRL
     *
     * @return the value of T_SB_ZNYC_DYHGQ.ZEDDRL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getZeddrl() {
        return zeddrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.ZEDDRL
     *
     * @param zeddrl the value for T_SB_ZNYC_DYHGQ.ZEDDRL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZeddrl(BigDecimal zeddrl) {
        this.zeddrl = zeddrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.DRQJS
     *
     * @return the value of T_SB_ZNYC_DYHGQ.DRQJS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public Integer getDrqjs() {
        return drqjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.DRQJS
     *
     * @param drqjs the value for T_SB_ZNYC_DYHGQ.DRQJS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setDrqjs(Integer drqjs) {
        this.drqjs = drqjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.SJDRL
     *
     * @return the value of T_SB_ZNYC_DYHGQ.SJDRL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getSjdrl() {
        return sjdrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.SJDRL
     *
     * @param sjdrl the value for T_SB_ZNYC_DYHGQ.SJDRL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSjdrl(BigDecimal sjdrl) {
        this.sjdrl = sjdrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.ZJDRL
     *
     * @return the value of T_SB_ZNYC_DYHGQ.ZJDRL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getZjdrl() {
        return zjdrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.ZJDRL
     *
     * @param zjdrl the value for T_SB_ZNYC_DYHGQ.ZJDRL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZjdrl(BigDecimal zjdrl) {
        this.zjdrl = zjdrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.XJC1DRL
     *
     * @return the value of T_SB_ZNYC_DYHGQ.XJC1DRL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getXjc1drl() {
        return xjc1drl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.XJC1DRL
     *
     * @param xjc1drl the value for T_SB_ZNYC_DYHGQ.XJC1DRL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setXjc1drl(BigDecimal xjc1drl) {
        this.xjc1drl = xjc1drl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.XJC2DRL
     *
     * @return the value of T_SB_ZNYC_DYHGQ.XJC2DRL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getXjc2drl() {
        return xjc2drl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.XJC2DRL
     *
     * @param xjc2drl the value for T_SB_ZNYC_DYHGQ.XJC2DRL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setXjc2drl(BigDecimal xjc2drl) {
        this.xjc2drl = xjc2drl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.SF6QTEDYL
     *
     * @return the value of T_SB_ZNYC_DYHGQ.SF6QTEDYL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getSf6qtedyl() {
        return sf6qtedyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.SF6QTEDYL
     *
     * @param sf6qtedyl the value for T_SB_ZNYC_DYHGQ.SF6QTEDYL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSf6qtedyl(BigDecimal sf6qtedyl) {
        this.sf6qtedyl = sf6qtedyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.SF6QTBJYL
     *
     * @return the value of T_SB_ZNYC_DYHGQ.SF6QTBJYL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getSf6qtbjyl() {
        return sf6qtbjyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.SF6QTBJYL
     *
     * @param sf6qtbjyl the value for T_SB_ZNYC_DYHGQ.SF6QTBJYL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSf6qtbjyl(BigDecimal sf6qtbjyl) {
        this.sf6qtbjyl = sf6qtbjyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.MFJG
     *
     * @return the value of T_SB_ZNYC_DYHGQ.MFJG
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getMfjg() {
        return mfjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.MFJG
     *
     * @param mfjg the value for T_SB_ZNYC_DYHGQ.MFJG
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setMfjg(String mfjg) {
        this.mfjg = mfjg == null ? null : mfjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.JYSP
     *
     * @return the value of T_SB_ZNYC_DYHGQ.JYSP
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getJysp() {
        return jysp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.JYSP
     *
     * @param jysp the value for T_SB_ZNYC_DYHGQ.JYSP
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setJysp(String jysp) {
        this.jysp = jysp == null ? null : jysp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.ECRZSLCL
     *
     * @return the value of T_SB_ZNYC_DYHGQ.ECRZSLCL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public Integer getEcrzslcl() {
        return ecrzslcl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.ECRZSLCL
     *
     * @param ecrzslcl the value for T_SB_ZNYC_DYHGQ.ECRZSLCL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setEcrzslcl(Integer ecrzslcl) {
        this.ecrzslcl = ecrzslcl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.ECRZSLBH
     *
     * @return the value of T_SB_ZNYC_DYHGQ.ECRZSLBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public Integer getEcrzslbh() {
        return ecrzslbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.ECRZSLBH
     *
     * @param ecrzslbh the value for T_SB_ZNYC_DYHGQ.ECRZSLBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setEcrzslbh(Integer ecrzslbh) {
        this.ecrzslbh = ecrzslbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.GD
     *
     * @return the value of T_SB_ZNYC_DYHGQ.GD
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getGd() {
        return gd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.GD
     *
     * @param gd the value for T_SB_ZNYC_DYHGQ.GD
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setGd(BigDecimal gd) {
        this.gd = gd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.SSZF
     *
     * @return the value of T_SB_ZNYC_DYHGQ.SSZF
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSszf() {
        return sszf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.SSZF
     *
     * @param sszf the value for T_SB_ZNYC_DYHGQ.SSZF
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSszf(String sszf) {
        this.sszf = sszf == null ? null : sszf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.EDKLZJDY
     *
     * @return the value of T_SB_ZNYC_DYHGQ.EDKLZJDY
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getEdklzjdy() {
        return edklzjdy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.EDKLZJDY
     *
     * @param edklzjdy the value for T_SB_ZNYC_DYHGQ.EDKLZJDY
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setEdklzjdy(BigDecimal edklzjdy) {
        this.edklzjdy = edklzjdy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.SCFYB
     *
     * @return the value of T_SB_ZNYC_DYHGQ.SCFYB
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getScfyb() {
        return scfyb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.SCFYB
     *
     * @param scfyb the value for T_SB_ZNYC_DYHGQ.SCFYB
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setScfyb(String scfyb) {
        this.scfyb = scfyb == null ? null : scfyb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.SJDRQBH
     *
     * @return the value of T_SB_ZNYC_DYHGQ.SJDRQBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSjdrqbh() {
        return sjdrqbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.SJDRQBH
     *
     * @param sjdrqbh the value for T_SB_ZNYC_DYHGQ.SJDRQBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSjdrqbh(String sjdrqbh) {
        this.sjdrqbh = sjdrqbh == null ? null : sjdrqbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.SJDRQXS
     *
     * @return the value of T_SB_ZNYC_DYHGQ.SJDRQXS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSjdrqxs() {
        return sjdrqxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.SJDRQXS
     *
     * @param sjdrqxs the value for T_SB_ZNYC_DYHGQ.SJDRQXS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSjdrqxs(String sjdrqxs) {
        this.sjdrqxs = sjdrqxs == null ? null : sjdrqxs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.ZJDRQBH
     *
     * @return the value of T_SB_ZNYC_DYHGQ.ZJDRQBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZjdrqbh() {
        return zjdrqbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.ZJDRQBH
     *
     * @param zjdrqbh the value for T_SB_ZNYC_DYHGQ.ZJDRQBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZjdrqbh(String zjdrqbh) {
        this.zjdrqbh = zjdrqbh == null ? null : zjdrqbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.ZJDRQXS
     *
     * @return the value of T_SB_ZNYC_DYHGQ.ZJDRQXS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZjdrqxs() {
        return zjdrqxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.ZJDRQXS
     *
     * @param zjdrqxs the value for T_SB_ZNYC_DYHGQ.ZJDRQXS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZjdrqxs(String zjdrqxs) {
        this.zjdrqxs = zjdrqxs == null ? null : zjdrqxs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.XJC1DRQBH
     *
     * @return the value of T_SB_ZNYC_DYHGQ.XJC1DRQBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getXjc1drqbh() {
        return xjc1drqbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.XJC1DRQBH
     *
     * @param xjc1drqbh the value for T_SB_ZNYC_DYHGQ.XJC1DRQBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setXjc1drqbh(String xjc1drqbh) {
        this.xjc1drqbh = xjc1drqbh == null ? null : xjc1drqbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.XJC1DRQXS
     *
     * @return the value of T_SB_ZNYC_DYHGQ.XJC1DRQXS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getXjc1drqxs() {
        return xjc1drqxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.XJC1DRQXS
     *
     * @param xjc1drqxs the value for T_SB_ZNYC_DYHGQ.XJC1DRQXS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setXjc1drqxs(String xjc1drqxs) {
        this.xjc1drqxs = xjc1drqxs == null ? null : xjc1drqxs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.XJC2DRQBH
     *
     * @return the value of T_SB_ZNYC_DYHGQ.XJC2DRQBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getXjc2drqbh() {
        return xjc2drqbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.XJC2DRQBH
     *
     * @param xjc2drqbh the value for T_SB_ZNYC_DYHGQ.XJC2DRQBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setXjc2drqbh(String xjc2drqbh) {
        this.xjc2drqbh = xjc2drqbh == null ? null : xjc2drqbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.ZCXZ
     *
     * @return the value of T_SB_ZNYC_DYHGQ.ZCXZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZcxz() {
        return zcxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.ZCXZ
     *
     * @param zcxz the value for T_SB_ZNYC_DYHGQ.ZCXZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZcxz(String zcxz) {
        this.zcxz = zcxz == null ? null : zcxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.XJC2DRQXS
     *
     * @return the value of T_SB_ZNYC_DYHGQ.XJC2DRQXS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getXjc2drqxs() {
        return xjc2drqxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.XJC2DRQXS
     *
     * @param xjc2drqxs the value for T_SB_ZNYC_DYHGQ.XJC2DRQXS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setXjc2drqxs(String xjc2drqxs) {
        this.xjc2drqxs = xjc2drqxs == null ? null : xjc2drqxs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.YCJ
     *
     * @return the value of T_SB_ZNYC_DYHGQ.YCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getYcj() {
        return ycj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.YCJ
     *
     * @param ycj the value for T_SB_ZNYC_DYHGQ.YCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setYcj(String ycj) {
        this.ycj = ycj == null ? null : ycj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.YZ
     *
     * @return the value of T_SB_ZNYC_DYHGQ.YZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getYz() {
        return yz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.YZ
     *
     * @param yz the value for T_SB_ZNYC_DYHGQ.YZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setYz(BigDecimal yz) {
        this.yz = yz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.SF6QTZL
     *
     * @return the value of T_SB_ZNYC_DYHGQ.SF6QTZL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getSf6qtzl() {
        return sf6qtzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.SF6QTZL
     *
     * @param sf6qtzl the value for T_SB_ZNYC_DYHGQ.SF6QTZL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSf6qtzl(BigDecimal sf6qtzl) {
        this.sf6qtzl = sf6qtzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.ZQJCL
     *
     * @return the value of T_SB_ZNYC_DYHGQ.ZQJCL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZqjcl() {
        return zqjcl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.ZQJCL
     *
     * @param zqjcl the value for T_SB_ZNYC_DYHGQ.ZQJCL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZqjcl(String zqjcl) {
        this.zqjcl = zqjcl == null ? null : zqjcl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.ZQJBH
     *
     * @return the value of T_SB_ZNYC_DYHGQ.ZQJBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZqjbh() {
        return zqjbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.ZQJBH
     *
     * @param zqjbh the value for T_SB_ZNYC_DYHGQ.ZQJBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZqjbh(String zqjbh) {
        this.zqjbh = zqjbh == null ? null : zqjbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.EDSCRLCL
     *
     * @return the value of T_SB_ZNYC_DYHGQ.EDSCRLCL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getEdscrlcl() {
        return edscrlcl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.EDSCRLCL
     *
     * @param edscrlcl the value for T_SB_ZNYC_DYHGQ.EDSCRLCL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setEdscrlcl(BigDecimal edscrlcl) {
        this.edscrlcl = edscrlcl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.EDSCRLBH
     *
     * @return the value of T_SB_ZNYC_DYHGQ.EDSCRLBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getEdscrlbh() {
        return edscrlbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.EDSCRLBH
     *
     * @param edscrlbh the value for T_SB_ZNYC_DYHGQ.EDSCRLBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setEdscrlbh(BigDecimal edscrlbh) {
        this.edscrlbh = edscrlbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.TYRQ
     *
     * @return the value of T_SB_ZNYC_DYHGQ.TYRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public Date getTyrq() {
        return tyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.TYRQ
     *
     * @param tyrq the value for T_SB_ZNYC_DYHGQ.TYRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setTyrq(Date tyrq) {
        this.tyrq = tyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.ZCDW
     *
     * @return the value of T_SB_ZNYC_DYHGQ.ZCDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZcdw() {
        return zcdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.ZCDW
     *
     * @param zcdw the value for T_SB_ZNYC_DYHGQ.ZCDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZcdw(String zcdw) {
        this.zcdw = zcdw == null ? null : zcdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.DYDJ
     *
     * @return the value of T_SB_ZNYC_DYHGQ.DYDJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getDydj() {
        return dydj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.DYDJ
     *
     * @param dydj the value for T_SB_ZNYC_DYHGQ.DYDJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setDydj(String dydj) {
        this.dydj = dydj == null ? null : dydj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.ZHDQKGGMC
     *
     * @return the value of T_SB_ZNYC_DYHGQ.ZHDQKGGMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZhdqkggmc() {
        return zhdqkggmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.ZHDQKGGMC
     *
     * @param zhdqkggmc the value for T_SB_ZNYC_DYHGQ.ZHDQKGGMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZhdqkggmc(String zhdqkggmc) {
        this.zhdqkggmc = zhdqkggmc == null ? null : zhdqkggmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.ECXHSCXS
     *
     * @return the value of T_SB_ZNYC_DYHGQ.ECXHSCXS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getEcxhscxs() {
        return ecxhscxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.ECXHSCXS
     *
     * @param ecxhscxs the value for T_SB_ZNYC_DYHGQ.ECXHSCXS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setEcxhscxs(String ecxhscxs) {
        this.ecxhscxs = ecxhscxs == null ? null : ecxhscxs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.LX
     *
     * @return the value of T_SB_ZNYC_DYHGQ.LX
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getLx() {
        return lx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.LX
     *
     * @param lx the value for T_SB_ZNYC_DYHGQ.LX
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setLx(String lx) {
        this.lx = lx == null ? null : lx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.YH
     *
     * @return the value of T_SB_ZNYC_DYHGQ.YH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getYh() {
        return yh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.YH
     *
     * @param yh the value for T_SB_ZNYC_DYHGQ.YH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setYh(String yh) {
        this.yh = yh == null ? null : yh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.ZZ
     *
     * @return the value of T_SB_ZNYC_DYHGQ.ZZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getZz() {
        return zz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.ZZ
     *
     * @param zz the value for T_SB_ZNYC_DYHGQ.ZZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZz(BigDecimal zz) {
        this.zz = zz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.SSDS
     *
     * @return the value of T_SB_ZNYC_DYHGQ.SSDS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSsds() {
        return ssds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.SSDS
     *
     * @param ssds the value for T_SB_ZNYC_DYHGQ.SSDS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSsds(String ssds) {
        this.ssds = ssds == null ? null : ssds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.WHBZ
     *
     * @return the value of T_SB_ZNYC_DYHGQ.WHBZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getWhbz() {
        return whbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.WHBZ
     *
     * @param whbz the value for T_SB_ZNYC_DYHGQ.WHBZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setWhbz(String whbz) {
        this.whbz = whbz == null ? null : whbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.SFDW
     *
     * @return the value of T_SB_ZNYC_DYHGQ.SFDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSfdw() {
        return sfdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.SFDW
     *
     * @param sfdw the value for T_SB_ZNYC_DYHGQ.SFDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSfdw(String sfdw) {
        this.sfdw = sfdw == null ? null : sfdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.EDECRL
     *
     * @return the value of T_SB_ZNYC_DYHGQ.EDECRL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getEdecrl() {
        return edecrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.EDECRL
     *
     * @param edecrl the value for T_SB_ZNYC_DYHGQ.EDECRL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setEdecrl(BigDecimal edecrl) {
        this.edecrl = edecrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.ZQDJ
     *
     * @return the value of T_SB_ZNYC_DYHGQ.ZQDJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZqdj() {
        return zqdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.ZQDJ
     *
     * @param zqdj the value for T_SB_ZNYC_DYHGQ.ZQDJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZqdj(String zqdj) {
        this.zqdj = zqdj == null ? null : zqdj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.BZ
     *
     * @return the value of T_SB_ZNYC_DYHGQ.BZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.BZ
     *
     * @param bz the value for T_SB_ZNYC_DYHGQ.BZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.DJSJ
     *
     * @return the value of T_SB_ZNYC_DYHGQ.DJSJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public Date getDjsj() {
        return djsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.DJSJ
     *
     * @param djsj the value for T_SB_ZNYC_DYHGQ.DJSJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setDjsj(Date djsj) {
        this.djsj = djsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.SBZR
     *
     * @return the value of T_SB_ZNYC_DYHGQ.SBZR
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSbzr() {
        return sbzr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.SBZR
     *
     * @param sbzr the value for T_SB_ZNYC_DYHGQ.SBZR
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSbzr(String sbzr) {
        this.sbzr = sbzr == null ? null : sbzr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.YWDWMC
     *
     * @return the value of T_SB_ZNYC_DYHGQ.YWDWMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getYwdwmc() {
        return ywdwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.YWDWMC
     *
     * @param ywdwmc the value for T_SB_ZNYC_DYHGQ.YWDWMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setYwdwmc(String ywdwmc) {
        this.ywdwmc = ywdwmc == null ? null : ywdwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.SSDSMC
     *
     * @return the value of T_SB_ZNYC_DYHGQ.SSDSMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSsdsmc() {
        return ssdsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.SSDSMC
     *
     * @param ssdsmc the value for T_SB_ZNYC_DYHGQ.SSDSMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSsdsmc(String ssdsmc) {
        this.ssdsmc = ssdsmc == null ? null : ssdsmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.SBZRMC
     *
     * @return the value of T_SB_ZNYC_DYHGQ.SBZRMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSbzrmc() {
        return sbzrmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.SBZRMC
     *
     * @param sbzrmc the value for T_SB_ZNYC_DYHGQ.SBZRMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSbzrmc(String sbzrmc) {
        this.sbzrmc = sbzrmc == null ? null : sbzrmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.ZCDWMC
     *
     * @return the value of T_SB_ZNYC_DYHGQ.ZCDWMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZcdwmc() {
        return zcdwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.ZCDWMC
     *
     * @param zcdwmc the value for T_SB_ZNYC_DYHGQ.ZCDWMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZcdwmc(String zcdwmc) {
        this.zcdwmc = zcdwmc == null ? null : zcdwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.WHBZMC
     *
     * @return the value of T_SB_ZNYC_DYHGQ.WHBZMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getWhbzmc() {
        return whbzmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.WHBZMC
     *
     * @param whbzmc the value for T_SB_ZNYC_DYHGQ.WHBZMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setWhbzmc(String whbzmc) {
        this.whbzmc = whbzmc == null ? null : whbzmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.SFNW
     *
     * @return the value of T_SB_ZNYC_DYHGQ.SFNW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSfnw() {
        return sfnw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.SFNW
     *
     * @param sfnw the value for T_SB_ZNYC_DYHGQ.SFNW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSfnw(String sfnw) {
        this.sfnw = sfnw == null ? null : sfnw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.DQTZ
     *
     * @return the value of T_SB_ZNYC_DYHGQ.DQTZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getDqtz() {
        return dqtz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.DQTZ
     *
     * @param dqtz the value for T_SB_ZNYC_DYHGQ.DQTZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setDqtz(String dqtz) {
        this.dqtz = dqtz == null ? null : dqtz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.SBPBS
     *
     * @return the value of T_SB_ZNYC_DYHGQ.SBPBS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSbpbs() {
        return sbpbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.SBPBS
     *
     * @param sbpbs the value for T_SB_ZNYC_DYHGQ.SBPBS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSbpbs(String sbpbs) {
        this.sbpbs = sbpbs == null ? null : sbpbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.CLBB
     *
     * @return the value of T_SB_ZNYC_DYHGQ.CLBB
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getClbb() {
        return clbb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.CLBB
     *
     * @param clbb the value for T_SB_ZNYC_DYHGQ.CLBB
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setClbb(String clbb) {
        this.clbb = clbb == null ? null : clbb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.BHBB
     *
     * @return the value of T_SB_ZNYC_DYHGQ.BHBB
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getBhbb() {
        return bhbb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.BHBB
     *
     * @param bhbb the value for T_SB_ZNYC_DYHGQ.BHBB
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setBhbb(String bhbb) {
        this.bhbb = bhbb == null ? null : bhbb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.FBZT
     *
     * @return the value of T_SB_ZNYC_DYHGQ.FBZT
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getFbzt() {
        return fbzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.FBZT
     *
     * @param fbzt the value for T_SB_ZNYC_DYHGQ.FBZT
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setFbzt(String fbzt) {
        this.fbzt = fbzt == null ? null : fbzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.ERPWBSBM
     *
     * @return the value of T_SB_ZNYC_DYHGQ.ERPWBSBM
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getErpwbsbm() {
        return erpwbsbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.ERPWBSBM
     *
     * @param erpwbsbm the value for T_SB_ZNYC_DYHGQ.ERPWBSBM
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setErpwbsbm(String erpwbsbm) {
        this.erpwbsbm = erpwbsbm == null ? null : erpwbsbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.ZYFL
     *
     * @return the value of T_SB_ZNYC_DYHGQ.ZYFL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZyfl() {
        return zyfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.ZYFL
     *
     * @param zyfl the value for T_SB_ZNYC_DYHGQ.ZYFL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZyfl(String zyfl) {
        this.zyfl = zyfl == null ? null : zyfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.XGHSBMC
     *
     * @return the value of T_SB_ZNYC_DYHGQ.XGHSBMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getXghsbmc() {
        return xghsbmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.XGHSBMC
     *
     * @param xghsbmc the value for T_SB_ZNYC_DYHGQ.XGHSBMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setXghsbmc(String xghsbmc) {
        this.xghsbmc = xghsbmc == null ? null : xghsbmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_DYHGQ.SFYC
     *
     * @return the value of T_SB_ZNYC_DYHGQ.SFYC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSfyc() {
        return sfyc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_DYHGQ.SFYC
     *
     * @param sfyc the value for T_SB_ZNYC_DYHGQ.SFYC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSfyc(String sfyc) {
        this.sfyc = sfyc == null ? null : sfyc.trim();
    }
}