package com.lnsoft.module.pms.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TSbZnycFhkg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.OBJ_ID
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String objId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.SBBM
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String sbbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.DXMPYXKID
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String dxmpyxkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.SBMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String sbmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.JGDY
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String jgdy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.TYRQ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private Date tyrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.KGZY
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String kgzy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.MHJZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String mhjz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.CZFS
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String czfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.EDDL
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private BigDecimal eddl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.ZCBH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String zcbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.YXBH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String yxbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.SSZF
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String sszf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.DYDJ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String dydj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.XH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.SCCJ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String sccj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.CCBH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String ccbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.CCRQ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private Date ccrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.ZCDW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String zcdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.ZCXZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String zcxz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.YWDW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String ywdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.WHBZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String whbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.SFDW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String sfdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.YXZT
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String yxzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.SSDS
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String ssds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.ZHSBLX
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String zhsblx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.SFWSGW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String sfwsgw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.EDDY
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String eddy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.BZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.DJSJ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private Date djsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.SBZR
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String sbzr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.ZCDWMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String zcdwmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.WHBZMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String whbzmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.SBZRMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String sbzrmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.SSDSMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String ssdsmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.YWDWMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String ywdwmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.SFNW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String sfnw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.DQTZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String dqtz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.SJSBID
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String sjsbid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.WBSBH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String wbsbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.WBSMS
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String wbsms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.SBZJFS
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String sbzjfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.ZHDQKGGMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String zhdqkggmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.SBPBS
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String sbpbs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.ZDKDDL
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private BigDecimal zdkddl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.FBZT
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String fbzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.ERPWBSBM
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String erpwbsbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.ZYFL
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String zyfl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.XGHSBMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String xghsbmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.SSDKX
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String ssdkx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZNYC_FHKG.SSKXXD
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    private String sskxxd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.OBJ_ID
     *
     * @return the value of T_SB_ZNYC_FHKG.OBJ_ID
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getObjId() {
        return objId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.OBJ_ID
     *
     * @param objId the value for T_SB_ZNYC_FHKG.OBJ_ID
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setObjId(String objId) {
        this.objId = objId == null ? null : objId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.SBBM
     *
     * @return the value of T_SB_ZNYC_FHKG.SBBM
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSbbm() {
        return sbbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.SBBM
     *
     * @param sbbm the value for T_SB_ZNYC_FHKG.SBBM
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSbbm(String sbbm) {
        this.sbbm = sbbm == null ? null : sbbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.DXMPYXKID
     *
     * @return the value of T_SB_ZNYC_FHKG.DXMPYXKID
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getDxmpyxkid() {
        return dxmpyxkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.DXMPYXKID
     *
     * @param dxmpyxkid the value for T_SB_ZNYC_FHKG.DXMPYXKID
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setDxmpyxkid(String dxmpyxkid) {
        this.dxmpyxkid = dxmpyxkid == null ? null : dxmpyxkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.SBMC
     *
     * @return the value of T_SB_ZNYC_FHKG.SBMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSbmc() {
        return sbmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.SBMC
     *
     * @param sbmc the value for T_SB_ZNYC_FHKG.SBMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSbmc(String sbmc) {
        this.sbmc = sbmc == null ? null : sbmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.JGDY
     *
     * @return the value of T_SB_ZNYC_FHKG.JGDY
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getJgdy() {
        return jgdy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.JGDY
     *
     * @param jgdy the value for T_SB_ZNYC_FHKG.JGDY
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setJgdy(String jgdy) {
        this.jgdy = jgdy == null ? null : jgdy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.TYRQ
     *
     * @return the value of T_SB_ZNYC_FHKG.TYRQ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public Date getTyrq() {
        return tyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.TYRQ
     *
     * @param tyrq the value for T_SB_ZNYC_FHKG.TYRQ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setTyrq(Date tyrq) {
        this.tyrq = tyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.KGZY
     *
     * @return the value of T_SB_ZNYC_FHKG.KGZY
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getKgzy() {
        return kgzy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.KGZY
     *
     * @param kgzy the value for T_SB_ZNYC_FHKG.KGZY
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setKgzy(String kgzy) {
        this.kgzy = kgzy == null ? null : kgzy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.MHJZ
     *
     * @return the value of T_SB_ZNYC_FHKG.MHJZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getMhjz() {
        return mhjz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.MHJZ
     *
     * @param mhjz the value for T_SB_ZNYC_FHKG.MHJZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setMhjz(String mhjz) {
        this.mhjz = mhjz == null ? null : mhjz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.CZFS
     *
     * @return the value of T_SB_ZNYC_FHKG.CZFS
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getCzfs() {
        return czfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.CZFS
     *
     * @param czfs the value for T_SB_ZNYC_FHKG.CZFS
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setCzfs(String czfs) {
        this.czfs = czfs == null ? null : czfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.EDDL
     *
     * @return the value of T_SB_ZNYC_FHKG.EDDL
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public BigDecimal getEddl() {
        return eddl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.EDDL
     *
     * @param eddl the value for T_SB_ZNYC_FHKG.EDDL
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setEddl(BigDecimal eddl) {
        this.eddl = eddl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.ZCBH
     *
     * @return the value of T_SB_ZNYC_FHKG.ZCBH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getZcbh() {
        return zcbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.ZCBH
     *
     * @param zcbh the value for T_SB_ZNYC_FHKG.ZCBH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setZcbh(String zcbh) {
        this.zcbh = zcbh == null ? null : zcbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.YXBH
     *
     * @return the value of T_SB_ZNYC_FHKG.YXBH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getYxbh() {
        return yxbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.YXBH
     *
     * @param yxbh the value for T_SB_ZNYC_FHKG.YXBH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setYxbh(String yxbh) {
        this.yxbh = yxbh == null ? null : yxbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.SSZF
     *
     * @return the value of T_SB_ZNYC_FHKG.SSZF
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSszf() {
        return sszf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.SSZF
     *
     * @param sszf the value for T_SB_ZNYC_FHKG.SSZF
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSszf(String sszf) {
        this.sszf = sszf == null ? null : sszf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.DYDJ
     *
     * @return the value of T_SB_ZNYC_FHKG.DYDJ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getDydj() {
        return dydj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.DYDJ
     *
     * @param dydj the value for T_SB_ZNYC_FHKG.DYDJ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setDydj(String dydj) {
        this.dydj = dydj == null ? null : dydj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.XH
     *
     * @return the value of T_SB_ZNYC_FHKG.XH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.XH
     *
     * @param xh the value for T_SB_ZNYC_FHKG.XH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setXh(String xh) {
        this.xh = xh == null ? null : xh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.SCCJ
     *
     * @return the value of T_SB_ZNYC_FHKG.SCCJ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSccj() {
        return sccj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.SCCJ
     *
     * @param sccj the value for T_SB_ZNYC_FHKG.SCCJ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSccj(String sccj) {
        this.sccj = sccj == null ? null : sccj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.CCBH
     *
     * @return the value of T_SB_ZNYC_FHKG.CCBH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getCcbh() {
        return ccbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.CCBH
     *
     * @param ccbh the value for T_SB_ZNYC_FHKG.CCBH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setCcbh(String ccbh) {
        this.ccbh = ccbh == null ? null : ccbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.CCRQ
     *
     * @return the value of T_SB_ZNYC_FHKG.CCRQ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public Date getCcrq() {
        return ccrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.CCRQ
     *
     * @param ccrq the value for T_SB_ZNYC_FHKG.CCRQ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setCcrq(Date ccrq) {
        this.ccrq = ccrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.ZCDW
     *
     * @return the value of T_SB_ZNYC_FHKG.ZCDW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getZcdw() {
        return zcdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.ZCDW
     *
     * @param zcdw the value for T_SB_ZNYC_FHKG.ZCDW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setZcdw(String zcdw) {
        this.zcdw = zcdw == null ? null : zcdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.ZCXZ
     *
     * @return the value of T_SB_ZNYC_FHKG.ZCXZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getZcxz() {
        return zcxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.ZCXZ
     *
     * @param zcxz the value for T_SB_ZNYC_FHKG.ZCXZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setZcxz(String zcxz) {
        this.zcxz = zcxz == null ? null : zcxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.YWDW
     *
     * @return the value of T_SB_ZNYC_FHKG.YWDW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getYwdw() {
        return ywdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.YWDW
     *
     * @param ywdw the value for T_SB_ZNYC_FHKG.YWDW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setYwdw(String ywdw) {
        this.ywdw = ywdw == null ? null : ywdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.WHBZ
     *
     * @return the value of T_SB_ZNYC_FHKG.WHBZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getWhbz() {
        return whbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.WHBZ
     *
     * @param whbz the value for T_SB_ZNYC_FHKG.WHBZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setWhbz(String whbz) {
        this.whbz = whbz == null ? null : whbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.SFDW
     *
     * @return the value of T_SB_ZNYC_FHKG.SFDW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSfdw() {
        return sfdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.SFDW
     *
     * @param sfdw the value for T_SB_ZNYC_FHKG.SFDW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSfdw(String sfdw) {
        this.sfdw = sfdw == null ? null : sfdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.YXZT
     *
     * @return the value of T_SB_ZNYC_FHKG.YXZT
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getYxzt() {
        return yxzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.YXZT
     *
     * @param yxzt the value for T_SB_ZNYC_FHKG.YXZT
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setYxzt(String yxzt) {
        this.yxzt = yxzt == null ? null : yxzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.SSDS
     *
     * @return the value of T_SB_ZNYC_FHKG.SSDS
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSsds() {
        return ssds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.SSDS
     *
     * @param ssds the value for T_SB_ZNYC_FHKG.SSDS
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSsds(String ssds) {
        this.ssds = ssds == null ? null : ssds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.ZHSBLX
     *
     * @return the value of T_SB_ZNYC_FHKG.ZHSBLX
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getZhsblx() {
        return zhsblx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.ZHSBLX
     *
     * @param zhsblx the value for T_SB_ZNYC_FHKG.ZHSBLX
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setZhsblx(String zhsblx) {
        this.zhsblx = zhsblx == null ? null : zhsblx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.SFWSGW
     *
     * @return the value of T_SB_ZNYC_FHKG.SFWSGW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSfwsgw() {
        return sfwsgw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.SFWSGW
     *
     * @param sfwsgw the value for T_SB_ZNYC_FHKG.SFWSGW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSfwsgw(String sfwsgw) {
        this.sfwsgw = sfwsgw == null ? null : sfwsgw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.EDDY
     *
     * @return the value of T_SB_ZNYC_FHKG.EDDY
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getEddy() {
        return eddy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.EDDY
     *
     * @param eddy the value for T_SB_ZNYC_FHKG.EDDY
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setEddy(String eddy) {
        this.eddy = eddy == null ? null : eddy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.BZ
     *
     * @return the value of T_SB_ZNYC_FHKG.BZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.BZ
     *
     * @param bz the value for T_SB_ZNYC_FHKG.BZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.DJSJ
     *
     * @return the value of T_SB_ZNYC_FHKG.DJSJ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public Date getDjsj() {
        return djsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.DJSJ
     *
     * @param djsj the value for T_SB_ZNYC_FHKG.DJSJ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setDjsj(Date djsj) {
        this.djsj = djsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.SBZR
     *
     * @return the value of T_SB_ZNYC_FHKG.SBZR
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSbzr() {
        return sbzr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.SBZR
     *
     * @param sbzr the value for T_SB_ZNYC_FHKG.SBZR
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSbzr(String sbzr) {
        this.sbzr = sbzr == null ? null : sbzr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.ZCDWMC
     *
     * @return the value of T_SB_ZNYC_FHKG.ZCDWMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getZcdwmc() {
        return zcdwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.ZCDWMC
     *
     * @param zcdwmc the value for T_SB_ZNYC_FHKG.ZCDWMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setZcdwmc(String zcdwmc) {
        this.zcdwmc = zcdwmc == null ? null : zcdwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.WHBZMC
     *
     * @return the value of T_SB_ZNYC_FHKG.WHBZMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getWhbzmc() {
        return whbzmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.WHBZMC
     *
     * @param whbzmc the value for T_SB_ZNYC_FHKG.WHBZMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setWhbzmc(String whbzmc) {
        this.whbzmc = whbzmc == null ? null : whbzmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.SBZRMC
     *
     * @return the value of T_SB_ZNYC_FHKG.SBZRMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSbzrmc() {
        return sbzrmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.SBZRMC
     *
     * @param sbzrmc the value for T_SB_ZNYC_FHKG.SBZRMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSbzrmc(String sbzrmc) {
        this.sbzrmc = sbzrmc == null ? null : sbzrmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.SSDSMC
     *
     * @return the value of T_SB_ZNYC_FHKG.SSDSMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSsdsmc() {
        return ssdsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.SSDSMC
     *
     * @param ssdsmc the value for T_SB_ZNYC_FHKG.SSDSMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSsdsmc(String ssdsmc) {
        this.ssdsmc = ssdsmc == null ? null : ssdsmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.YWDWMC
     *
     * @return the value of T_SB_ZNYC_FHKG.YWDWMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getYwdwmc() {
        return ywdwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.YWDWMC
     *
     * @param ywdwmc the value for T_SB_ZNYC_FHKG.YWDWMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setYwdwmc(String ywdwmc) {
        this.ywdwmc = ywdwmc == null ? null : ywdwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.SFNW
     *
     * @return the value of T_SB_ZNYC_FHKG.SFNW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSfnw() {
        return sfnw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.SFNW
     *
     * @param sfnw the value for T_SB_ZNYC_FHKG.SFNW
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSfnw(String sfnw) {
        this.sfnw = sfnw == null ? null : sfnw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.DQTZ
     *
     * @return the value of T_SB_ZNYC_FHKG.DQTZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getDqtz() {
        return dqtz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.DQTZ
     *
     * @param dqtz the value for T_SB_ZNYC_FHKG.DQTZ
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setDqtz(String dqtz) {
        this.dqtz = dqtz == null ? null : dqtz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.SJSBID
     *
     * @return the value of T_SB_ZNYC_FHKG.SJSBID
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSjsbid() {
        return sjsbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.SJSBID
     *
     * @param sjsbid the value for T_SB_ZNYC_FHKG.SJSBID
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSjsbid(String sjsbid) {
        this.sjsbid = sjsbid == null ? null : sjsbid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.WBSBH
     *
     * @return the value of T_SB_ZNYC_FHKG.WBSBH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getWbsbh() {
        return wbsbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.WBSBH
     *
     * @param wbsbh the value for T_SB_ZNYC_FHKG.WBSBH
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setWbsbh(String wbsbh) {
        this.wbsbh = wbsbh == null ? null : wbsbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.WBSMS
     *
     * @return the value of T_SB_ZNYC_FHKG.WBSMS
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getWbsms() {
        return wbsms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.WBSMS
     *
     * @param wbsms the value for T_SB_ZNYC_FHKG.WBSMS
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setWbsms(String wbsms) {
        this.wbsms = wbsms == null ? null : wbsms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.SBZJFS
     *
     * @return the value of T_SB_ZNYC_FHKG.SBZJFS
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSbzjfs() {
        return sbzjfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.SBZJFS
     *
     * @param sbzjfs the value for T_SB_ZNYC_FHKG.SBZJFS
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSbzjfs(String sbzjfs) {
        this.sbzjfs = sbzjfs == null ? null : sbzjfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.ZHDQKGGMC
     *
     * @return the value of T_SB_ZNYC_FHKG.ZHDQKGGMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getZhdqkggmc() {
        return zhdqkggmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.ZHDQKGGMC
     *
     * @param zhdqkggmc the value for T_SB_ZNYC_FHKG.ZHDQKGGMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setZhdqkggmc(String zhdqkggmc) {
        this.zhdqkggmc = zhdqkggmc == null ? null : zhdqkggmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.SBPBS
     *
     * @return the value of T_SB_ZNYC_FHKG.SBPBS
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSbpbs() {
        return sbpbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.SBPBS
     *
     * @param sbpbs the value for T_SB_ZNYC_FHKG.SBPBS
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSbpbs(String sbpbs) {
        this.sbpbs = sbpbs == null ? null : sbpbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.ZDKDDL
     *
     * @return the value of T_SB_ZNYC_FHKG.ZDKDDL
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public BigDecimal getZdkddl() {
        return zdkddl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.ZDKDDL
     *
     * @param zdkddl the value for T_SB_ZNYC_FHKG.ZDKDDL
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setZdkddl(BigDecimal zdkddl) {
        this.zdkddl = zdkddl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.FBZT
     *
     * @return the value of T_SB_ZNYC_FHKG.FBZT
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getFbzt() {
        return fbzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.FBZT
     *
     * @param fbzt the value for T_SB_ZNYC_FHKG.FBZT
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setFbzt(String fbzt) {
        this.fbzt = fbzt == null ? null : fbzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.ERPWBSBM
     *
     * @return the value of T_SB_ZNYC_FHKG.ERPWBSBM
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getErpwbsbm() {
        return erpwbsbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.ERPWBSBM
     *
     * @param erpwbsbm the value for T_SB_ZNYC_FHKG.ERPWBSBM
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setErpwbsbm(String erpwbsbm) {
        this.erpwbsbm = erpwbsbm == null ? null : erpwbsbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.ZYFL
     *
     * @return the value of T_SB_ZNYC_FHKG.ZYFL
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getZyfl() {
        return zyfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.ZYFL
     *
     * @param zyfl the value for T_SB_ZNYC_FHKG.ZYFL
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setZyfl(String zyfl) {
        this.zyfl = zyfl == null ? null : zyfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.XGHSBMC
     *
     * @return the value of T_SB_ZNYC_FHKG.XGHSBMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getXghsbmc() {
        return xghsbmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.XGHSBMC
     *
     * @param xghsbmc the value for T_SB_ZNYC_FHKG.XGHSBMC
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setXghsbmc(String xghsbmc) {
        this.xghsbmc = xghsbmc == null ? null : xghsbmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.SSDKX
     *
     * @return the value of T_SB_ZNYC_FHKG.SSDKX
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSsdkx() {
        return ssdkx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.SSDKX
     *
     * @param ssdkx the value for T_SB_ZNYC_FHKG.SSDKX
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSsdkx(String ssdkx) {
        this.ssdkx = ssdkx == null ? null : ssdkx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZNYC_FHKG.SSKXXD
     *
     * @return the value of T_SB_ZNYC_FHKG.SSKXXD
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public String getSskxxd() {
        return sskxxd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZNYC_FHKG.SSKXXD
     *
     * @param sskxxd the value for T_SB_ZNYC_FHKG.SSKXXD
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    public void setSskxxd(String sskxxd) {
        this.sskxxd = sskxxd == null ? null : sskxxd.trim();
    }
}