package com.lnsoft.module.pms.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TSbZlsbHlzfwlqxt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.OBJ_ID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String objId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.SBBM
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sbbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.XTMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String xtmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.YXBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String yxbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.SSDS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String ssds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.YWDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String ywdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.WHBZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String whbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.HLZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String hlz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.YXZT
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String yxzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.TYRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private Date tyrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.ZCXZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zcxz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.ZCDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zcdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.ZCBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zcbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.WBSBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String wbsbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.WBSMS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String wbsms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.SBZJFS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sbzjfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.XH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.SCCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sccj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.ZZGJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zzgj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.CCRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private Date ccrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.CCBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String ccbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.GSSCCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String gssccj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.GSXH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String gsxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.GSGCS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private Integer gsgcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.GJXH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String gjxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.GJMTGSFJTS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private Integer gjmtgsfjts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.FSDJSCCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String fsdjsccj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.FSDJXH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String fsdjxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.FJSL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private Integer fjsl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.BPQSCCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String bpqsccj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.BPQXH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String bpqxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.BPQSRDYDY
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal bpqsrdydy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.BPQDYSRPL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal bpqdysrpl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.BPQSL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal bpqsl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.PDJKZGPDKZGSL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal pdjkzgpdkzgsl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.DJSCCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String djsccj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.DJXH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String djxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.DJSL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private Integer djsl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.DJEDGLW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal djedglw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.DJEDDY
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal djeddy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.DJEDDLA
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private BigDecimal djeddla;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.BYCSCCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String bycsccj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.BYCGG
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String bycgg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.BYCSL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private Integer bycsl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.DJSJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private Date djsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.SBZR
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sbzr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.SSDSMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String ssdsmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.YWDWMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String ywdwmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.WHBZMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String whbzmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.ZCDWMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zcdwmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.BZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.SSZFMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String sszfmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.FBZT
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String fbzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.SSJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String ssj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.GDD
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String gdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.ERPWBSBM
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String erpwbsbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.ZYFL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String zyfl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SB_ZLSB_HLZFWLQXT.XGHSBMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    private String xghsbmc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.OBJ_ID
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.OBJ_ID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getObjId() {
        return objId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.OBJ_ID
     *
     * @param objId the value for T_SB_ZLSB_HLZFWLQXT.OBJ_ID
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setObjId(String objId) {
        this.objId = objId == null ? null : objId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.SBBM
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.SBBM
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSbbm() {
        return sbbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.SBBM
     *
     * @param sbbm the value for T_SB_ZLSB_HLZFWLQXT.SBBM
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSbbm(String sbbm) {
        this.sbbm = sbbm == null ? null : sbbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.XTMC
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.XTMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getXtmc() {
        return xtmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.XTMC
     *
     * @param xtmc the value for T_SB_ZLSB_HLZFWLQXT.XTMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setXtmc(String xtmc) {
        this.xtmc = xtmc == null ? null : xtmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.YXBH
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.YXBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getYxbh() {
        return yxbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.YXBH
     *
     * @param yxbh the value for T_SB_ZLSB_HLZFWLQXT.YXBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setYxbh(String yxbh) {
        this.yxbh = yxbh == null ? null : yxbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.SSDS
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.SSDS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSsds() {
        return ssds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.SSDS
     *
     * @param ssds the value for T_SB_ZLSB_HLZFWLQXT.SSDS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSsds(String ssds) {
        this.ssds = ssds == null ? null : ssds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.YWDW
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.YWDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getYwdw() {
        return ywdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.YWDW
     *
     * @param ywdw the value for T_SB_ZLSB_HLZFWLQXT.YWDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setYwdw(String ywdw) {
        this.ywdw = ywdw == null ? null : ywdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.WHBZ
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.WHBZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getWhbz() {
        return whbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.WHBZ
     *
     * @param whbz the value for T_SB_ZLSB_HLZFWLQXT.WHBZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setWhbz(String whbz) {
        this.whbz = whbz == null ? null : whbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.HLZ
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.HLZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getHlz() {
        return hlz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.HLZ
     *
     * @param hlz the value for T_SB_ZLSB_HLZFWLQXT.HLZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setHlz(String hlz) {
        this.hlz = hlz == null ? null : hlz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.YXZT
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.YXZT
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getYxzt() {
        return yxzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.YXZT
     *
     * @param yxzt the value for T_SB_ZLSB_HLZFWLQXT.YXZT
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setYxzt(String yxzt) {
        this.yxzt = yxzt == null ? null : yxzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.TYRQ
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.TYRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public Date getTyrq() {
        return tyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.TYRQ
     *
     * @param tyrq the value for T_SB_ZLSB_HLZFWLQXT.TYRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setTyrq(Date tyrq) {
        this.tyrq = tyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.ZCXZ
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.ZCXZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZcxz() {
        return zcxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.ZCXZ
     *
     * @param zcxz the value for T_SB_ZLSB_HLZFWLQXT.ZCXZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZcxz(String zcxz) {
        this.zcxz = zcxz == null ? null : zcxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.ZCDW
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.ZCDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZcdw() {
        return zcdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.ZCDW
     *
     * @param zcdw the value for T_SB_ZLSB_HLZFWLQXT.ZCDW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZcdw(String zcdw) {
        this.zcdw = zcdw == null ? null : zcdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.ZCBH
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.ZCBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZcbh() {
        return zcbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.ZCBH
     *
     * @param zcbh the value for T_SB_ZLSB_HLZFWLQXT.ZCBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZcbh(String zcbh) {
        this.zcbh = zcbh == null ? null : zcbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.WBSBH
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.WBSBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getWbsbh() {
        return wbsbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.WBSBH
     *
     * @param wbsbh the value for T_SB_ZLSB_HLZFWLQXT.WBSBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setWbsbh(String wbsbh) {
        this.wbsbh = wbsbh == null ? null : wbsbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.WBSMS
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.WBSMS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getWbsms() {
        return wbsms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.WBSMS
     *
     * @param wbsms the value for T_SB_ZLSB_HLZFWLQXT.WBSMS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setWbsms(String wbsms) {
        this.wbsms = wbsms == null ? null : wbsms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.SBZJFS
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.SBZJFS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSbzjfs() {
        return sbzjfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.SBZJFS
     *
     * @param sbzjfs the value for T_SB_ZLSB_HLZFWLQXT.SBZJFS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSbzjfs(String sbzjfs) {
        this.sbzjfs = sbzjfs == null ? null : sbzjfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.XH
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.XH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.XH
     *
     * @param xh the value for T_SB_ZLSB_HLZFWLQXT.XH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setXh(String xh) {
        this.xh = xh == null ? null : xh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.SCCJ
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.SCCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSccj() {
        return sccj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.SCCJ
     *
     * @param sccj the value for T_SB_ZLSB_HLZFWLQXT.SCCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSccj(String sccj) {
        this.sccj = sccj == null ? null : sccj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.ZZGJ
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.ZZGJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZzgj() {
        return zzgj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.ZZGJ
     *
     * @param zzgj the value for T_SB_ZLSB_HLZFWLQXT.ZZGJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZzgj(String zzgj) {
        this.zzgj = zzgj == null ? null : zzgj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.CCRQ
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.CCRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public Date getCcrq() {
        return ccrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.CCRQ
     *
     * @param ccrq the value for T_SB_ZLSB_HLZFWLQXT.CCRQ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setCcrq(Date ccrq) {
        this.ccrq = ccrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.CCBH
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.CCBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getCcbh() {
        return ccbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.CCBH
     *
     * @param ccbh the value for T_SB_ZLSB_HLZFWLQXT.CCBH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setCcbh(String ccbh) {
        this.ccbh = ccbh == null ? null : ccbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.GSSCCJ
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.GSSCCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getGssccj() {
        return gssccj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.GSSCCJ
     *
     * @param gssccj the value for T_SB_ZLSB_HLZFWLQXT.GSSCCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setGssccj(String gssccj) {
        this.gssccj = gssccj == null ? null : gssccj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.GSXH
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.GSXH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getGsxh() {
        return gsxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.GSXH
     *
     * @param gsxh the value for T_SB_ZLSB_HLZFWLQXT.GSXH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setGsxh(String gsxh) {
        this.gsxh = gsxh == null ? null : gsxh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.GSGCS
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.GSGCS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public Integer getGsgcs() {
        return gsgcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.GSGCS
     *
     * @param gsgcs the value for T_SB_ZLSB_HLZFWLQXT.GSGCS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setGsgcs(Integer gsgcs) {
        this.gsgcs = gsgcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.GJXH
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.GJXH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getGjxh() {
        return gjxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.GJXH
     *
     * @param gjxh the value for T_SB_ZLSB_HLZFWLQXT.GJXH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setGjxh(String gjxh) {
        this.gjxh = gjxh == null ? null : gjxh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.GJMTGSFJTS
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.GJMTGSFJTS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public Integer getGjmtgsfjts() {
        return gjmtgsfjts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.GJMTGSFJTS
     *
     * @param gjmtgsfjts the value for T_SB_ZLSB_HLZFWLQXT.GJMTGSFJTS
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setGjmtgsfjts(Integer gjmtgsfjts) {
        this.gjmtgsfjts = gjmtgsfjts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.FSDJSCCJ
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.FSDJSCCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getFsdjsccj() {
        return fsdjsccj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.FSDJSCCJ
     *
     * @param fsdjsccj the value for T_SB_ZLSB_HLZFWLQXT.FSDJSCCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setFsdjsccj(String fsdjsccj) {
        this.fsdjsccj = fsdjsccj == null ? null : fsdjsccj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.FSDJXH
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.FSDJXH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getFsdjxh() {
        return fsdjxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.FSDJXH
     *
     * @param fsdjxh the value for T_SB_ZLSB_HLZFWLQXT.FSDJXH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setFsdjxh(String fsdjxh) {
        this.fsdjxh = fsdjxh == null ? null : fsdjxh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.FJSL
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.FJSL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public Integer getFjsl() {
        return fjsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.FJSL
     *
     * @param fjsl the value for T_SB_ZLSB_HLZFWLQXT.FJSL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setFjsl(Integer fjsl) {
        this.fjsl = fjsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.BPQSCCJ
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.BPQSCCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getBpqsccj() {
        return bpqsccj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.BPQSCCJ
     *
     * @param bpqsccj the value for T_SB_ZLSB_HLZFWLQXT.BPQSCCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setBpqsccj(String bpqsccj) {
        this.bpqsccj = bpqsccj == null ? null : bpqsccj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.BPQXH
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.BPQXH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getBpqxh() {
        return bpqxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.BPQXH
     *
     * @param bpqxh the value for T_SB_ZLSB_HLZFWLQXT.BPQXH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setBpqxh(String bpqxh) {
        this.bpqxh = bpqxh == null ? null : bpqxh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.BPQSRDYDY
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.BPQSRDYDY
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getBpqsrdydy() {
        return bpqsrdydy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.BPQSRDYDY
     *
     * @param bpqsrdydy the value for T_SB_ZLSB_HLZFWLQXT.BPQSRDYDY
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setBpqsrdydy(BigDecimal bpqsrdydy) {
        this.bpqsrdydy = bpqsrdydy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.BPQDYSRPL
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.BPQDYSRPL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getBpqdysrpl() {
        return bpqdysrpl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.BPQDYSRPL
     *
     * @param bpqdysrpl the value for T_SB_ZLSB_HLZFWLQXT.BPQDYSRPL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setBpqdysrpl(BigDecimal bpqdysrpl) {
        this.bpqdysrpl = bpqdysrpl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.BPQSL
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.BPQSL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getBpqsl() {
        return bpqsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.BPQSL
     *
     * @param bpqsl the value for T_SB_ZLSB_HLZFWLQXT.BPQSL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setBpqsl(BigDecimal bpqsl) {
        this.bpqsl = bpqsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.PDJKZGPDKZGSL
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.PDJKZGPDKZGSL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getPdjkzgpdkzgsl() {
        return pdjkzgpdkzgsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.PDJKZGPDKZGSL
     *
     * @param pdjkzgpdkzgsl the value for T_SB_ZLSB_HLZFWLQXT.PDJKZGPDKZGSL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setPdjkzgpdkzgsl(BigDecimal pdjkzgpdkzgsl) {
        this.pdjkzgpdkzgsl = pdjkzgpdkzgsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.DJSCCJ
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.DJSCCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getDjsccj() {
        return djsccj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.DJSCCJ
     *
     * @param djsccj the value for T_SB_ZLSB_HLZFWLQXT.DJSCCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setDjsccj(String djsccj) {
        this.djsccj = djsccj == null ? null : djsccj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.DJXH
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.DJXH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getDjxh() {
        return djxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.DJXH
     *
     * @param djxh the value for T_SB_ZLSB_HLZFWLQXT.DJXH
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setDjxh(String djxh) {
        this.djxh = djxh == null ? null : djxh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.DJSL
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.DJSL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public Integer getDjsl() {
        return djsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.DJSL
     *
     * @param djsl the value for T_SB_ZLSB_HLZFWLQXT.DJSL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setDjsl(Integer djsl) {
        this.djsl = djsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.DJEDGLW
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.DJEDGLW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getDjedglw() {
        return djedglw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.DJEDGLW
     *
     * @param djedglw the value for T_SB_ZLSB_HLZFWLQXT.DJEDGLW
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setDjedglw(BigDecimal djedglw) {
        this.djedglw = djedglw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.DJEDDY
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.DJEDDY
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getDjeddy() {
        return djeddy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.DJEDDY
     *
     * @param djeddy the value for T_SB_ZLSB_HLZFWLQXT.DJEDDY
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setDjeddy(BigDecimal djeddy) {
        this.djeddy = djeddy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.DJEDDLA
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.DJEDDLA
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public BigDecimal getDjeddla() {
        return djeddla;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.DJEDDLA
     *
     * @param djeddla the value for T_SB_ZLSB_HLZFWLQXT.DJEDDLA
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setDjeddla(BigDecimal djeddla) {
        this.djeddla = djeddla;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.BYCSCCJ
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.BYCSCCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getBycsccj() {
        return bycsccj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.BYCSCCJ
     *
     * @param bycsccj the value for T_SB_ZLSB_HLZFWLQXT.BYCSCCJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setBycsccj(String bycsccj) {
        this.bycsccj = bycsccj == null ? null : bycsccj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.BYCGG
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.BYCGG
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getBycgg() {
        return bycgg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.BYCGG
     *
     * @param bycgg the value for T_SB_ZLSB_HLZFWLQXT.BYCGG
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setBycgg(String bycgg) {
        this.bycgg = bycgg == null ? null : bycgg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.BYCSL
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.BYCSL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public Integer getBycsl() {
        return bycsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.BYCSL
     *
     * @param bycsl the value for T_SB_ZLSB_HLZFWLQXT.BYCSL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setBycsl(Integer bycsl) {
        this.bycsl = bycsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.DJSJ
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.DJSJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public Date getDjsj() {
        return djsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.DJSJ
     *
     * @param djsj the value for T_SB_ZLSB_HLZFWLQXT.DJSJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setDjsj(Date djsj) {
        this.djsj = djsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.SBZR
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.SBZR
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSbzr() {
        return sbzr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.SBZR
     *
     * @param sbzr the value for T_SB_ZLSB_HLZFWLQXT.SBZR
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSbzr(String sbzr) {
        this.sbzr = sbzr == null ? null : sbzr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.SSDSMC
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.SSDSMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSsdsmc() {
        return ssdsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.SSDSMC
     *
     * @param ssdsmc the value for T_SB_ZLSB_HLZFWLQXT.SSDSMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSsdsmc(String ssdsmc) {
        this.ssdsmc = ssdsmc == null ? null : ssdsmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.YWDWMC
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.YWDWMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getYwdwmc() {
        return ywdwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.YWDWMC
     *
     * @param ywdwmc the value for T_SB_ZLSB_HLZFWLQXT.YWDWMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setYwdwmc(String ywdwmc) {
        this.ywdwmc = ywdwmc == null ? null : ywdwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.WHBZMC
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.WHBZMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getWhbzmc() {
        return whbzmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.WHBZMC
     *
     * @param whbzmc the value for T_SB_ZLSB_HLZFWLQXT.WHBZMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setWhbzmc(String whbzmc) {
        this.whbzmc = whbzmc == null ? null : whbzmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.ZCDWMC
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.ZCDWMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZcdwmc() {
        return zcdwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.ZCDWMC
     *
     * @param zcdwmc the value for T_SB_ZLSB_HLZFWLQXT.ZCDWMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZcdwmc(String zcdwmc) {
        this.zcdwmc = zcdwmc == null ? null : zcdwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.BZ
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.BZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.BZ
     *
     * @param bz the value for T_SB_ZLSB_HLZFWLQXT.BZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.SSZFMC
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.SSZFMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSszfmc() {
        return sszfmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.SSZFMC
     *
     * @param sszfmc the value for T_SB_ZLSB_HLZFWLQXT.SSZFMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSszfmc(String sszfmc) {
        this.sszfmc = sszfmc == null ? null : sszfmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.FBZT
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.FBZT
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getFbzt() {
        return fbzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.FBZT
     *
     * @param fbzt the value for T_SB_ZLSB_HLZFWLQXT.FBZT
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setFbzt(String fbzt) {
        this.fbzt = fbzt == null ? null : fbzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.SSJ
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.SSJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getSsj() {
        return ssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.SSJ
     *
     * @param ssj the value for T_SB_ZLSB_HLZFWLQXT.SSJ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setSsj(String ssj) {
        this.ssj = ssj == null ? null : ssj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.GDD
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.GDD
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getGdd() {
        return gdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.GDD
     *
     * @param gdd the value for T_SB_ZLSB_HLZFWLQXT.GDD
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setGdd(String gdd) {
        this.gdd = gdd == null ? null : gdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.ERPWBSBM
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.ERPWBSBM
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getErpwbsbm() {
        return erpwbsbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.ERPWBSBM
     *
     * @param erpwbsbm the value for T_SB_ZLSB_HLZFWLQXT.ERPWBSBM
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setErpwbsbm(String erpwbsbm) {
        this.erpwbsbm = erpwbsbm == null ? null : erpwbsbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.ZYFL
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.ZYFL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getZyfl() {
        return zyfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.ZYFL
     *
     * @param zyfl the value for T_SB_ZLSB_HLZFWLQXT.ZYFL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setZyfl(String zyfl) {
        this.zyfl = zyfl == null ? null : zyfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SB_ZLSB_HLZFWLQXT.XGHSBMC
     *
     * @return the value of T_SB_ZLSB_HLZFWLQXT.XGHSBMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public String getXghsbmc() {
        return xghsbmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SB_ZLSB_HLZFWLQXT.XGHSBMC
     *
     * @param xghsbmc the value for T_SB_ZLSB_HLZFWLQXT.XGHSBMC
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    public void setXghsbmc(String xghsbmc) {
        this.xghsbmc = xghsbmc == null ? null : xghsbmc.trim();
    }
}