package com.lnsoft.module.gzlb.mapper;

import com.lnsoft.module.gzlb.pojo.TQxxtReportinfo;
import com.lnsoft.module.gzlb.pojo.TQxxtReportinfoExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TQxxtReportinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QXXT_REPORTINFO
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    int countByExample(TQxxtReportinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QXXT_REPORTINFO
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    int deleteByExample(TQxxtReportinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QXXT_REPORTINFO
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QXXT_REPORTINFO
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    int insert(TQxxtReportinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QXXT_REPORTINFO
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    int insertSelective(TQxxtReportinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QXXT_REPORTINFO
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    List<TQxxtReportinfo> selectByExample(TQxxtReportinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QXXT_REPORTINFO
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    TQxxtReportinfo selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QXXT_REPORTINFO
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") TQxxtReportinfo record, @Param("example") TQxxtReportinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QXXT_REPORTINFO
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    int updateByExample(@Param("record") TQxxtReportinfo record, @Param("example") TQxxtReportinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QXXT_REPORTINFO
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    int updateByPrimaryKeySelective(TQxxtReportinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QXXT_REPORTINFO
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    int updateByPrimaryKey(TQxxtReportinfo record);
}