package com.lnsoft.module.gzlb.mapper;

import com.lnsoft.module.gzlb.pojo.TQxxtRecordfile;
import com.lnsoft.module.gzlb.pojo.TQxxtRecordfileExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TQxxtRecordfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QXXT_RECORDFILE
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    int countByExample(TQxxtRecordfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QXXT_RECORDFILE
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    int deleteByExample(TQxxtRecordfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QXXT_RECORDFILE
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QXXT_RECORDFILE
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    int insert(TQxxtRecordfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QXXT_RECORDFILE
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    int insertSelective(TQxxtRecordfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QXXT_RECORDFILE
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    List<TQxxtRecordfile> selectByExample(TQxxtRecordfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QXXT_RECORDFILE
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    TQxxtRecordfile selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QXXT_RECORDFILE
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") TQxxtRecordfile record, @Param("example") TQxxtRecordfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QXXT_RECORDFILE
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    int updateByExample(@Param("record") TQxxtRecordfile record, @Param("example") TQxxtRecordfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QXXT_RECORDFILE
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    int updateByPrimaryKeySelective(TQxxtRecordfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QXXT_RECORDFILE
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    int updateByPrimaryKey(TQxxtRecordfile record);
}