package com.lnsoft.module.gzlb.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TJdbhGzlbMainExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_JDBH_GZLB_MAIN
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_JDBH_GZLB_MAIN
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_JDBH_GZLB_MAIN
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JDBH_GZLB_MAIN
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    public TJdbhGzlbMainExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JDBH_GZLB_MAIN
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JDBH_GZLB_MAIN
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JDBH_GZLB_MAIN
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JDBH_GZLB_MAIN
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JDBH_GZLB_MAIN
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JDBH_GZLB_MAIN
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JDBH_GZLB_MAIN
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JDBH_GZLB_MAIN
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JDBH_GZLB_MAIN
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JDBH_GZLB_MAIN
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_JDBH_GZLB_MAIN
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSjdzsjIsNull() {
            addCriterion("SJDZSJ is null");
            return (Criteria) this;
        }

        public Criteria andSjdzsjIsNotNull() {
            addCriterion("SJDZSJ is not null");
            return (Criteria) this;
        }

        public Criteria andSjdzsjEqualTo(String value) {
            addCriterion("SJDZSJ =", value, "sjdzsj");
            return (Criteria) this;
        }

        public Criteria andSjdzsjNotEqualTo(String value) {
            addCriterion("SJDZSJ <>", value, "sjdzsj");
            return (Criteria) this;
        }

        public Criteria andSjdzsjGreaterThan(String value) {
            addCriterion("SJDZSJ >", value, "sjdzsj");
            return (Criteria) this;
        }

        public Criteria andSjdzsjGreaterThanOrEqualTo(String value) {
            addCriterion("SJDZSJ >=", value, "sjdzsj");
            return (Criteria) this;
        }

        public Criteria andSjdzsjLessThan(String value) {
            addCriterion("SJDZSJ <", value, "sjdzsj");
            return (Criteria) this;
        }

        public Criteria andSjdzsjLessThanOrEqualTo(String value) {
            addCriterion("SJDZSJ <=", value, "sjdzsj");
            return (Criteria) this;
        }

        public Criteria andSjdzsjLike(String value) {
            addCriterion("SJDZSJ like", value, "sjdzsj");
            return (Criteria) this;
        }

        public Criteria andSjdzsjNotLike(String value) {
            addCriterion("SJDZSJ not like", value, "sjdzsj");
            return (Criteria) this;
        }

        public Criteria andSjdzsjIn(List<String> values) {
            addCriterion("SJDZSJ in", values, "sjdzsj");
            return (Criteria) this;
        }

        public Criteria andSjdzsjNotIn(List<String> values) {
            addCriterion("SJDZSJ not in", values, "sjdzsj");
            return (Criteria) this;
        }

        public Criteria andSjdzsjBetween(String value1, String value2) {
            addCriterion("SJDZSJ between", value1, value2, "sjdzsj");
            return (Criteria) this;
        }

        public Criteria andSjdzsjNotBetween(String value1, String value2) {
            addCriterion("SJDZSJ not between", value1, value2, "sjdzsj");
            return (Criteria) this;
        }

        public Criteria andSjbssjIsNull() {
            addCriterion("SJBSSJ is null");
            return (Criteria) this;
        }

        public Criteria andSjbssjIsNotNull() {
            addCriterion("SJBSSJ is not null");
            return (Criteria) this;
        }

        public Criteria andSjbssjEqualTo(String value) {
            addCriterion("SJBSSJ =", value, "sjbssj");
            return (Criteria) this;
        }

        public Criteria andSjbssjNotEqualTo(String value) {
            addCriterion("SJBSSJ <>", value, "sjbssj");
            return (Criteria) this;
        }

        public Criteria andSjbssjGreaterThan(String value) {
            addCriterion("SJBSSJ >", value, "sjbssj");
            return (Criteria) this;
        }

        public Criteria andSjbssjGreaterThanOrEqualTo(String value) {
            addCriterion("SJBSSJ >=", value, "sjbssj");
            return (Criteria) this;
        }

        public Criteria andSjbssjLessThan(String value) {
            addCriterion("SJBSSJ <", value, "sjbssj");
            return (Criteria) this;
        }

        public Criteria andSjbssjLessThanOrEqualTo(String value) {
            addCriterion("SJBSSJ <=", value, "sjbssj");
            return (Criteria) this;
        }

        public Criteria andSjbssjLike(String value) {
            addCriterion("SJBSSJ like", value, "sjbssj");
            return (Criteria) this;
        }

        public Criteria andSjbssjNotLike(String value) {
            addCriterion("SJBSSJ not like", value, "sjbssj");
            return (Criteria) this;
        }

        public Criteria andSjbssjIn(List<String> values) {
            addCriterion("SJBSSJ in", values, "sjbssj");
            return (Criteria) this;
        }

        public Criteria andSjbssjNotIn(List<String> values) {
            addCriterion("SJBSSJ not in", values, "sjbssj");
            return (Criteria) this;
        }

        public Criteria andSjbssjBetween(String value1, String value2) {
            addCriterion("SJBSSJ between", value1, value2, "sjbssj");
            return (Criteria) this;
        }

        public Criteria andSjbssjNotBetween(String value1, String value2) {
            addCriterion("SJBSSJ not between", value1, value2, "sjbssj");
            return (Criteria) this;
        }

        public Criteria andSbsxIsNull() {
            addCriterion("SBSX is null");
            return (Criteria) this;
        }

        public Criteria andSbsxIsNotNull() {
            addCriterion("SBSX is not null");
            return (Criteria) this;
        }

        public Criteria andSbsxEqualTo(String value) {
            addCriterion("SBSX =", value, "sbsx");
            return (Criteria) this;
        }

        public Criteria andSbsxNotEqualTo(String value) {
            addCriterion("SBSX <>", value, "sbsx");
            return (Criteria) this;
        }

        public Criteria andSbsxGreaterThan(String value) {
            addCriterion("SBSX >", value, "sbsx");
            return (Criteria) this;
        }

        public Criteria andSbsxGreaterThanOrEqualTo(String value) {
            addCriterion("SBSX >=", value, "sbsx");
            return (Criteria) this;
        }

        public Criteria andSbsxLessThan(String value) {
            addCriterion("SBSX <", value, "sbsx");
            return (Criteria) this;
        }

        public Criteria andSbsxLessThanOrEqualTo(String value) {
            addCriterion("SBSX <=", value, "sbsx");
            return (Criteria) this;
        }

        public Criteria andSbsxLike(String value) {
            addCriterion("SBSX like", value, "sbsx");
            return (Criteria) this;
        }

        public Criteria andSbsxNotLike(String value) {
            addCriterion("SBSX not like", value, "sbsx");
            return (Criteria) this;
        }

        public Criteria andSbsxIn(List<String> values) {
            addCriterion("SBSX in", values, "sbsx");
            return (Criteria) this;
        }

        public Criteria andSbsxNotIn(List<String> values) {
            addCriterion("SBSX not in", values, "sbsx");
            return (Criteria) this;
        }

        public Criteria andSbsxBetween(String value1, String value2) {
            addCriterion("SBSX between", value1, value2, "sbsx");
            return (Criteria) this;
        }

        public Criteria andSbsxNotBetween(String value1, String value2) {
            addCriterion("SBSX not between", value1, value2, "sbsx");
            return (Criteria) this;
        }

        public Criteria andDydjIsNull() {
            addCriterion("DYDJ is null");
            return (Criteria) this;
        }

        public Criteria andDydjIsNotNull() {
            addCriterion("DYDJ is not null");
            return (Criteria) this;
        }

        public Criteria andDydjEqualTo(String value) {
            addCriterion("DYDJ =", value, "dydj");
            return (Criteria) this;
        }

        public Criteria andDydjNotEqualTo(String value) {
            addCriterion("DYDJ <>", value, "dydj");
            return (Criteria) this;
        }

        public Criteria andDydjGreaterThan(String value) {
            addCriterion("DYDJ >", value, "dydj");
            return (Criteria) this;
        }

        public Criteria andDydjGreaterThanOrEqualTo(String value) {
            addCriterion("DYDJ >=", value, "dydj");
            return (Criteria) this;
        }

        public Criteria andDydjLessThan(String value) {
            addCriterion("DYDJ <", value, "dydj");
            return (Criteria) this;
        }

        public Criteria andDydjLessThanOrEqualTo(String value) {
            addCriterion("DYDJ <=", value, "dydj");
            return (Criteria) this;
        }

        public Criteria andDydjLike(String value) {
            addCriterion("DYDJ like", value, "dydj");
            return (Criteria) this;
        }

        public Criteria andDydjNotLike(String value) {
            addCriterion("DYDJ not like", value, "dydj");
            return (Criteria) this;
        }

        public Criteria andDydjIn(List<String> values) {
            addCriterion("DYDJ in", values, "dydj");
            return (Criteria) this;
        }

        public Criteria andDydjNotIn(List<String> values) {
            addCriterion("DYDJ not in", values, "dydj");
            return (Criteria) this;
        }

        public Criteria andDydjBetween(String value1, String value2) {
            addCriterion("DYDJ between", value1, value2, "dydj");
            return (Criteria) this;
        }

        public Criteria andDydjNotBetween(String value1, String value2) {
            addCriterion("DYDJ not between", value1, value2, "dydj");
            return (Criteria) this;
        }

        public Criteria andSbddmcIsNull() {
            addCriterion("SBDDMC is null");
            return (Criteria) this;
        }

        public Criteria andSbddmcIsNotNull() {
            addCriterion("SBDDMC is not null");
            return (Criteria) this;
        }

        public Criteria andSbddmcEqualTo(String value) {
            addCriterion("SBDDMC =", value, "sbddmc");
            return (Criteria) this;
        }

        public Criteria andSbddmcNotEqualTo(String value) {
            addCriterion("SBDDMC <>", value, "sbddmc");
            return (Criteria) this;
        }

        public Criteria andSbddmcGreaterThan(String value) {
            addCriterion("SBDDMC >", value, "sbddmc");
            return (Criteria) this;
        }

        public Criteria andSbddmcGreaterThanOrEqualTo(String value) {
            addCriterion("SBDDMC >=", value, "sbddmc");
            return (Criteria) this;
        }

        public Criteria andSbddmcLessThan(String value) {
            addCriterion("SBDDMC <", value, "sbddmc");
            return (Criteria) this;
        }

        public Criteria andSbddmcLessThanOrEqualTo(String value) {
            addCriterion("SBDDMC <=", value, "sbddmc");
            return (Criteria) this;
        }

        public Criteria andSbddmcLike(String value) {
            addCriterion("SBDDMC like", value, "sbddmc");
            return (Criteria) this;
        }

        public Criteria andSbddmcNotLike(String value) {
            addCriterion("SBDDMC not like", value, "sbddmc");
            return (Criteria) this;
        }

        public Criteria andSbddmcIn(List<String> values) {
            addCriterion("SBDDMC in", values, "sbddmc");
            return (Criteria) this;
        }

        public Criteria andSbddmcNotIn(List<String> values) {
            addCriterion("SBDDMC not in", values, "sbddmc");
            return (Criteria) this;
        }

        public Criteria andSbddmcBetween(String value1, String value2) {
            addCriterion("SBDDMC between", value1, value2, "sbddmc");
            return (Criteria) this;
        }

        public Criteria andSbddmcNotBetween(String value1, String value2) {
            addCriterion("SBDDMC not between", value1, value2, "sbddmc");
            return (Criteria) this;
        }

        public Criteria andQkmsIsNull() {
            addCriterion("QKMS is null");
            return (Criteria) this;
        }

        public Criteria andQkmsIsNotNull() {
            addCriterion("QKMS is not null");
            return (Criteria) this;
        }

        public Criteria andQkmsEqualTo(String value) {
            addCriterion("QKMS =", value, "qkms");
            return (Criteria) this;
        }

        public Criteria andQkmsNotEqualTo(String value) {
            addCriterion("QKMS <>", value, "qkms");
            return (Criteria) this;
        }

        public Criteria andQkmsGreaterThan(String value) {
            addCriterion("QKMS >", value, "qkms");
            return (Criteria) this;
        }

        public Criteria andQkmsGreaterThanOrEqualTo(String value) {
            addCriterion("QKMS >=", value, "qkms");
            return (Criteria) this;
        }

        public Criteria andQkmsLessThan(String value) {
            addCriterion("QKMS <", value, "qkms");
            return (Criteria) this;
        }

        public Criteria andQkmsLessThanOrEqualTo(String value) {
            addCriterion("QKMS <=", value, "qkms");
            return (Criteria) this;
        }

        public Criteria andQkmsLike(String value) {
            addCriterion("QKMS like", value, "qkms");
            return (Criteria) this;
        }

        public Criteria andQkmsNotLike(String value) {
            addCriterion("QKMS not like", value, "qkms");
            return (Criteria) this;
        }

        public Criteria andQkmsIn(List<String> values) {
            addCriterion("QKMS in", values, "qkms");
            return (Criteria) this;
        }

        public Criteria andQkmsNotIn(List<String> values) {
            addCriterion("QKMS not in", values, "qkms");
            return (Criteria) this;
        }

        public Criteria andQkmsBetween(String value1, String value2) {
            addCriterion("QKMS between", value1, value2, "qkms");
            return (Criteria) this;
        }

        public Criteria andQkmsNotBetween(String value1, String value2) {
            addCriterion("QKMS not between", value1, value2, "qkms");
            return (Criteria) this;
        }

        public Criteria andXlsbqkmsIsNull() {
            addCriterion("XLSBQKMS is null");
            return (Criteria) this;
        }

        public Criteria andXlsbqkmsIsNotNull() {
            addCriterion("XLSBQKMS is not null");
            return (Criteria) this;
        }

        public Criteria andXlsbqkmsEqualTo(String value) {
            addCriterion("XLSBQKMS =", value, "xlsbqkms");
            return (Criteria) this;
        }

        public Criteria andXlsbqkmsNotEqualTo(String value) {
            addCriterion("XLSBQKMS <>", value, "xlsbqkms");
            return (Criteria) this;
        }

        public Criteria andXlsbqkmsGreaterThan(String value) {
            addCriterion("XLSBQKMS >", value, "xlsbqkms");
            return (Criteria) this;
        }

        public Criteria andXlsbqkmsGreaterThanOrEqualTo(String value) {
            addCriterion("XLSBQKMS >=", value, "xlsbqkms");
            return (Criteria) this;
        }

        public Criteria andXlsbqkmsLessThan(String value) {
            addCriterion("XLSBQKMS <", value, "xlsbqkms");
            return (Criteria) this;
        }

        public Criteria andXlsbqkmsLessThanOrEqualTo(String value) {
            addCriterion("XLSBQKMS <=", value, "xlsbqkms");
            return (Criteria) this;
        }

        public Criteria andXlsbqkmsLike(String value) {
            addCriterion("XLSBQKMS like", value, "xlsbqkms");
            return (Criteria) this;
        }

        public Criteria andXlsbqkmsNotLike(String value) {
            addCriterion("XLSBQKMS not like", value, "xlsbqkms");
            return (Criteria) this;
        }

        public Criteria andXlsbqkmsIn(List<String> values) {
            addCriterion("XLSBQKMS in", values, "xlsbqkms");
            return (Criteria) this;
        }

        public Criteria andXlsbqkmsNotIn(List<String> values) {
            addCriterion("XLSBQKMS not in", values, "xlsbqkms");
            return (Criteria) this;
        }

        public Criteria andXlsbqkmsBetween(String value1, String value2) {
            addCriterion("XLSBQKMS between", value1, value2, "xlsbqkms");
            return (Criteria) this;
        }

        public Criteria andXlsbqkmsNotBetween(String value1, String value2) {
            addCriterion("XLSBQKMS not between", value1, value2, "xlsbqkms");
            return (Criteria) this;
        }

        public Criteria andSjpjIsNull() {
            addCriterion("SJPJ is null");
            return (Criteria) this;
        }

        public Criteria andSjpjIsNotNull() {
            addCriterion("SJPJ is not null");
            return (Criteria) this;
        }

        public Criteria andSjpjEqualTo(String value) {
            addCriterion("SJPJ =", value, "sjpj");
            return (Criteria) this;
        }

        public Criteria andSjpjNotEqualTo(String value) {
            addCriterion("SJPJ <>", value, "sjpj");
            return (Criteria) this;
        }

        public Criteria andSjpjGreaterThan(String value) {
            addCriterion("SJPJ >", value, "sjpj");
            return (Criteria) this;
        }

        public Criteria andSjpjGreaterThanOrEqualTo(String value) {
            addCriterion("SJPJ >=", value, "sjpj");
            return (Criteria) this;
        }

        public Criteria andSjpjLessThan(String value) {
            addCriterion("SJPJ <", value, "sjpj");
            return (Criteria) this;
        }

        public Criteria andSjpjLessThanOrEqualTo(String value) {
            addCriterion("SJPJ <=", value, "sjpj");
            return (Criteria) this;
        }

        public Criteria andSjpjLike(String value) {
            addCriterion("SJPJ like", value, "sjpj");
            return (Criteria) this;
        }

        public Criteria andSjpjNotLike(String value) {
            addCriterion("SJPJ not like", value, "sjpj");
            return (Criteria) this;
        }

        public Criteria andSjpjIn(List<String> values) {
            addCriterion("SJPJ in", values, "sjpj");
            return (Criteria) this;
        }

        public Criteria andSjpjNotIn(List<String> values) {
            addCriterion("SJPJ not in", values, "sjpj");
            return (Criteria) this;
        }

        public Criteria andSjpjBetween(String value1, String value2) {
            addCriterion("SJPJ between", value1, value2, "sjpj");
            return (Criteria) this;
        }

        public Criteria andSjpjNotBetween(String value1, String value2) {
            addCriterion("SJPJ not between", value1, value2, "sjpj");
            return (Criteria) this;
        }

        public Criteria andSjdzsj1IsNull() {
            addCriterion("SJDZSJ1 is null");
            return (Criteria) this;
        }

        public Criteria andSjdzsj1IsNotNull() {
            addCriterion("SJDZSJ1 is not null");
            return (Criteria) this;
        }

        public Criteria andSjdzsj1EqualTo(Date value) {
            addCriterion("SJDZSJ1 =", value, "sjdzsj1");
            return (Criteria) this;
        }

        public Criteria andSjdzsj1NotEqualTo(Date value) {
            addCriterion("SJDZSJ1 <>", value, "sjdzsj1");
            return (Criteria) this;
        }

        public Criteria andSjdzsj1GreaterThan(Date value) {
            addCriterion("SJDZSJ1 >", value, "sjdzsj1");
            return (Criteria) this;
        }

        public Criteria andSjdzsj1GreaterThanOrEqualTo(Date value) {
            addCriterion("SJDZSJ1 >=", value, "sjdzsj1");
            return (Criteria) this;
        }

        public Criteria andSjdzsj1LessThan(Date value) {
            addCriterion("SJDZSJ1 <", value, "sjdzsj1");
            return (Criteria) this;
        }

        public Criteria andSjdzsj1LessThanOrEqualTo(Date value) {
            addCriterion("SJDZSJ1 <=", value, "sjdzsj1");
            return (Criteria) this;
        }

        public Criteria andSjdzsj1In(List<Date> values) {
            addCriterion("SJDZSJ1 in", values, "sjdzsj1");
            return (Criteria) this;
        }

        public Criteria andSjdzsj1NotIn(List<Date> values) {
            addCriterion("SJDZSJ1 not in", values, "sjdzsj1");
            return (Criteria) this;
        }

        public Criteria andSjdzsj1Between(Date value1, Date value2) {
            addCriterion("SJDZSJ1 between", value1, value2, "sjdzsj1");
            return (Criteria) this;
        }

        public Criteria andSjdzsj1NotBetween(Date value1, Date value2) {
            addCriterion("SJDZSJ1 not between", value1, value2, "sjdzsj1");
            return (Criteria) this;
        }

        public Criteria andInserttimeIsNull() {
            addCriterion("INSERTTIME is null");
            return (Criteria) this;
        }

        public Criteria andInserttimeIsNotNull() {
            addCriterion("INSERTTIME is not null");
            return (Criteria) this;
        }

        public Criteria andInserttimeEqualTo(Date value) {
            addCriterion("INSERTTIME =", value, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeNotEqualTo(Date value) {
            addCriterion("INSERTTIME <>", value, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeGreaterThan(Date value) {
            addCriterion("INSERTTIME >", value, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("INSERTTIME >=", value, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeLessThan(Date value) {
            addCriterion("INSERTTIME <", value, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeLessThanOrEqualTo(Date value) {
            addCriterion("INSERTTIME <=", value, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeIn(List<Date> values) {
            addCriterion("INSERTTIME in", values, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeNotIn(List<Date> values) {
            addCriterion("INSERTTIME not in", values, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeBetween(Date value1, Date value2) {
            addCriterion("INSERTTIME between", value1, value2, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeNotBetween(Date value1, Date value2) {
            addCriterion("INSERTTIME not between", value1, value2, "inserttime");
            return (Criteria) this;
        }

        public Criteria andPmssbidIsNull() {
            addCriterion("PMSSBID is null");
            return (Criteria) this;
        }

        public Criteria andPmssbidIsNotNull() {
            addCriterion("PMSSBID is not null");
            return (Criteria) this;
        }

        public Criteria andPmssbidEqualTo(String value) {
            addCriterion("PMSSBID =", value, "pmssbid");
            return (Criteria) this;
        }

        public Criteria andPmssbidNotEqualTo(String value) {
            addCriterion("PMSSBID <>", value, "pmssbid");
            return (Criteria) this;
        }

        public Criteria andPmssbidGreaterThan(String value) {
            addCriterion("PMSSBID >", value, "pmssbid");
            return (Criteria) this;
        }

        public Criteria andPmssbidGreaterThanOrEqualTo(String value) {
            addCriterion("PMSSBID >=", value, "pmssbid");
            return (Criteria) this;
        }

        public Criteria andPmssbidLessThan(String value) {
            addCriterion("PMSSBID <", value, "pmssbid");
            return (Criteria) this;
        }

        public Criteria andPmssbidLessThanOrEqualTo(String value) {
            addCriterion("PMSSBID <=", value, "pmssbid");
            return (Criteria) this;
        }

        public Criteria andPmssbidLike(String value) {
            addCriterion("PMSSBID like", value, "pmssbid");
            return (Criteria) this;
        }

        public Criteria andPmssbidNotLike(String value) {
            addCriterion("PMSSBID not like", value, "pmssbid");
            return (Criteria) this;
        }

        public Criteria andPmssbidIn(List<String> values) {
            addCriterion("PMSSBID in", values, "pmssbid");
            return (Criteria) this;
        }

        public Criteria andPmssbidNotIn(List<String> values) {
            addCriterion("PMSSBID not in", values, "pmssbid");
            return (Criteria) this;
        }

        public Criteria andPmssbidBetween(String value1, String value2) {
            addCriterion("PMSSBID between", value1, value2, "pmssbid");
            return (Criteria) this;
        }

        public Criteria andPmssbidNotBetween(String value1, String value2) {
            addCriterion("PMSSBID not between", value1, value2, "pmssbid");
            return (Criteria) this;
        }

        public Criteria andGzlxIsNull() {
            addCriterion("GZLX is null");
            return (Criteria) this;
        }

        public Criteria andGzlxIsNotNull() {
            addCriterion("GZLX is not null");
            return (Criteria) this;
        }

        public Criteria andGzlxEqualTo(String value) {
            addCriterion("GZLX =", value, "gzlx");
            return (Criteria) this;
        }

        public Criteria andGzlxNotEqualTo(String value) {
            addCriterion("GZLX <>", value, "gzlx");
            return (Criteria) this;
        }

        public Criteria andGzlxGreaterThan(String value) {
            addCriterion("GZLX >", value, "gzlx");
            return (Criteria) this;
        }

        public Criteria andGzlxGreaterThanOrEqualTo(String value) {
            addCriterion("GZLX >=", value, "gzlx");
            return (Criteria) this;
        }

        public Criteria andGzlxLessThan(String value) {
            addCriterion("GZLX <", value, "gzlx");
            return (Criteria) this;
        }

        public Criteria andGzlxLessThanOrEqualTo(String value) {
            addCriterion("GZLX <=", value, "gzlx");
            return (Criteria) this;
        }

        public Criteria andGzlxLike(String value) {
            addCriterion("GZLX like", value, "gzlx");
            return (Criteria) this;
        }

        public Criteria andGzlxNotLike(String value) {
            addCriterion("GZLX not like", value, "gzlx");
            return (Criteria) this;
        }

        public Criteria andGzlxIn(List<String> values) {
            addCriterion("GZLX in", values, "gzlx");
            return (Criteria) this;
        }

        public Criteria andGzlxNotIn(List<String> values) {
            addCriterion("GZLX not in", values, "gzlx");
            return (Criteria) this;
        }

        public Criteria andGzlxBetween(String value1, String value2) {
            addCriterion("GZLX between", value1, value2, "gzlx");
            return (Criteria) this;
        }

        public Criteria andGzlxNotBetween(String value1, String value2) {
            addCriterion("GZLX not between", value1, value2, "gzlx");
            return (Criteria) this;
        }

        public Criteria andSblxgfIsNull() {
            addCriterion("SBLXGF is null");
            return (Criteria) this;
        }

        public Criteria andSblxgfIsNotNull() {
            addCriterion("SBLXGF is not null");
            return (Criteria) this;
        }

        public Criteria andSblxgfEqualTo(String value) {
            addCriterion("SBLXGF =", value, "sblxgf");
            return (Criteria) this;
        }

        public Criteria andSblxgfNotEqualTo(String value) {
            addCriterion("SBLXGF <>", value, "sblxgf");
            return (Criteria) this;
        }

        public Criteria andSblxgfGreaterThan(String value) {
            addCriterion("SBLXGF >", value, "sblxgf");
            return (Criteria) this;
        }

        public Criteria andSblxgfGreaterThanOrEqualTo(String value) {
            addCriterion("SBLXGF >=", value, "sblxgf");
            return (Criteria) this;
        }

        public Criteria andSblxgfLessThan(String value) {
            addCriterion("SBLXGF <", value, "sblxgf");
            return (Criteria) this;
        }

        public Criteria andSblxgfLessThanOrEqualTo(String value) {
            addCriterion("SBLXGF <=", value, "sblxgf");
            return (Criteria) this;
        }

        public Criteria andSblxgfLike(String value) {
            addCriterion("SBLXGF like", value, "sblxgf");
            return (Criteria) this;
        }

        public Criteria andSblxgfNotLike(String value) {
            addCriterion("SBLXGF not like", value, "sblxgf");
            return (Criteria) this;
        }

        public Criteria andSblxgfIn(List<String> values) {
            addCriterion("SBLXGF in", values, "sblxgf");
            return (Criteria) this;
        }

        public Criteria andSblxgfNotIn(List<String> values) {
            addCriterion("SBLXGF not in", values, "sblxgf");
            return (Criteria) this;
        }

        public Criteria andSblxgfBetween(String value1, String value2) {
            addCriterion("SBLXGF between", value1, value2, "sblxgf");
            return (Criteria) this;
        }

        public Criteria andSblxgfNotBetween(String value1, String value2) {
            addCriterion("SBLXGF not between", value1, value2, "sblxgf");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_JDBH_GZLB_MAIN
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 16 16:23:22 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_JDBH_GZLB_MAIN
     *
     * @mbggenerated Fri Nov 16 16:23:22 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}