package com.lnsoft.module.ddjc.pojo;

public class DdjcKggztddyData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDJC_KGGZTDDY_DATA.SJID
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    private String sjid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDJC_KGGZTDDY_DATA.YSJL_ID
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    private String ysjlId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDJC_KGGZTDDY_DATA.XH
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    private String xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDJC_KGGZTDDY_DATA.DYDJ
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    private String dydj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDJC_KGGZTDDY_DATA.JGMC
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDJC_KGGZTDDY_DATA.SBMC
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    private String sbmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDJC_KGGZTDDY_DATA.JCDMC
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    private String jcdmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDJC_KGGZTDDY_DATA.JCBW
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    private String jcbw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDJC_KGGZTDDY_DATA.YSSJWJ
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    private String yssjwj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDJC_KGGZTDDY_DATA.BZZS
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    private String bzzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDJC_KGGZTDDY_DATA.ZDXHFZ
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    private String zdxhfz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDJC_KGGZTDDY_DATA.ZDXHFZWZ
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    private String zdxhfzwz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDJC_KGGZTDDY_DATA.XXMSYFX
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    private String xxmsyfx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDJC_KGGZTDDY_DATA.JL
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    private String jl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDJC_KGGZTDDY_DATA.SBID
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    private String sbid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDJC_KGGZTDDY_DATA.JCDID
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    private String jcdid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDJC_KGGZTDDY_DATA.SAVE_PATH
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    private String savePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDJC_KGGZTDDY_DATA.FHDL
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    private String fhdl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDJC_KGGZTDDY_DATA.SJID
     *
     * @return the value of DDJC_KGGZTDDY_DATA.SJID
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public String getSjid() {
        return sjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDJC_KGGZTDDY_DATA.SJID
     *
     * @param sjid the value for DDJC_KGGZTDDY_DATA.SJID
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public void setSjid(String sjid) {
        this.sjid = sjid == null ? null : sjid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDJC_KGGZTDDY_DATA.YSJL_ID
     *
     * @return the value of DDJC_KGGZTDDY_DATA.YSJL_ID
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public String getYsjlId() {
        return ysjlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDJC_KGGZTDDY_DATA.YSJL_ID
     *
     * @param ysjlId the value for DDJC_KGGZTDDY_DATA.YSJL_ID
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public void setYsjlId(String ysjlId) {
        this.ysjlId = ysjlId == null ? null : ysjlId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDJC_KGGZTDDY_DATA.XH
     *
     * @return the value of DDJC_KGGZTDDY_DATA.XH
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public String getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDJC_KGGZTDDY_DATA.XH
     *
     * @param xh the value for DDJC_KGGZTDDY_DATA.XH
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public void setXh(String xh) {
        this.xh = xh == null ? null : xh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDJC_KGGZTDDY_DATA.DYDJ
     *
     * @return the value of DDJC_KGGZTDDY_DATA.DYDJ
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public String getDydj() {
        return dydj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDJC_KGGZTDDY_DATA.DYDJ
     *
     * @param dydj the value for DDJC_KGGZTDDY_DATA.DYDJ
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public void setDydj(String dydj) {
        this.dydj = dydj == null ? null : dydj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDJC_KGGZTDDY_DATA.JGMC
     *
     * @return the value of DDJC_KGGZTDDY_DATA.JGMC
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDJC_KGGZTDDY_DATA.JGMC
     *
     * @param jgmc the value for DDJC_KGGZTDDY_DATA.JGMC
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDJC_KGGZTDDY_DATA.SBMC
     *
     * @return the value of DDJC_KGGZTDDY_DATA.SBMC
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public String getSbmc() {
        return sbmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDJC_KGGZTDDY_DATA.SBMC
     *
     * @param sbmc the value for DDJC_KGGZTDDY_DATA.SBMC
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public void setSbmc(String sbmc) {
        this.sbmc = sbmc == null ? null : sbmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDJC_KGGZTDDY_DATA.JCDMC
     *
     * @return the value of DDJC_KGGZTDDY_DATA.JCDMC
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public String getJcdmc() {
        return jcdmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDJC_KGGZTDDY_DATA.JCDMC
     *
     * @param jcdmc the value for DDJC_KGGZTDDY_DATA.JCDMC
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public void setJcdmc(String jcdmc) {
        this.jcdmc = jcdmc == null ? null : jcdmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDJC_KGGZTDDY_DATA.JCBW
     *
     * @return the value of DDJC_KGGZTDDY_DATA.JCBW
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public String getJcbw() {
        return jcbw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDJC_KGGZTDDY_DATA.JCBW
     *
     * @param jcbw the value for DDJC_KGGZTDDY_DATA.JCBW
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public void setJcbw(String jcbw) {
        this.jcbw = jcbw == null ? null : jcbw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDJC_KGGZTDDY_DATA.YSSJWJ
     *
     * @return the value of DDJC_KGGZTDDY_DATA.YSSJWJ
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public String getYssjwj() {
        return yssjwj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDJC_KGGZTDDY_DATA.YSSJWJ
     *
     * @param yssjwj the value for DDJC_KGGZTDDY_DATA.YSSJWJ
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public void setYssjwj(String yssjwj) {
        this.yssjwj = yssjwj == null ? null : yssjwj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDJC_KGGZTDDY_DATA.BZZS
     *
     * @return the value of DDJC_KGGZTDDY_DATA.BZZS
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public String getBzzs() {
        return bzzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDJC_KGGZTDDY_DATA.BZZS
     *
     * @param bzzs the value for DDJC_KGGZTDDY_DATA.BZZS
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public void setBzzs(String bzzs) {
        this.bzzs = bzzs == null ? null : bzzs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDJC_KGGZTDDY_DATA.ZDXHFZ
     *
     * @return the value of DDJC_KGGZTDDY_DATA.ZDXHFZ
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public String getZdxhfz() {
        return zdxhfz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDJC_KGGZTDDY_DATA.ZDXHFZ
     *
     * @param zdxhfz the value for DDJC_KGGZTDDY_DATA.ZDXHFZ
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public void setZdxhfz(String zdxhfz) {
        this.zdxhfz = zdxhfz == null ? null : zdxhfz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDJC_KGGZTDDY_DATA.ZDXHFZWZ
     *
     * @return the value of DDJC_KGGZTDDY_DATA.ZDXHFZWZ
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public String getZdxhfzwz() {
        return zdxhfzwz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDJC_KGGZTDDY_DATA.ZDXHFZWZ
     *
     * @param zdxhfzwz the value for DDJC_KGGZTDDY_DATA.ZDXHFZWZ
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public void setZdxhfzwz(String zdxhfzwz) {
        this.zdxhfzwz = zdxhfzwz == null ? null : zdxhfzwz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDJC_KGGZTDDY_DATA.XXMSYFX
     *
     * @return the value of DDJC_KGGZTDDY_DATA.XXMSYFX
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public String getXxmsyfx() {
        return xxmsyfx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDJC_KGGZTDDY_DATA.XXMSYFX
     *
     * @param xxmsyfx the value for DDJC_KGGZTDDY_DATA.XXMSYFX
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public void setXxmsyfx(String xxmsyfx) {
        this.xxmsyfx = xxmsyfx == null ? null : xxmsyfx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDJC_KGGZTDDY_DATA.JL
     *
     * @return the value of DDJC_KGGZTDDY_DATA.JL
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public String getJl() {
        return jl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDJC_KGGZTDDY_DATA.JL
     *
     * @param jl the value for DDJC_KGGZTDDY_DATA.JL
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public void setJl(String jl) {
        this.jl = jl == null ? null : jl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDJC_KGGZTDDY_DATA.SBID
     *
     * @return the value of DDJC_KGGZTDDY_DATA.SBID
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public String getSbid() {
        return sbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDJC_KGGZTDDY_DATA.SBID
     *
     * @param sbid the value for DDJC_KGGZTDDY_DATA.SBID
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public void setSbid(String sbid) {
        this.sbid = sbid == null ? null : sbid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDJC_KGGZTDDY_DATA.JCDID
     *
     * @return the value of DDJC_KGGZTDDY_DATA.JCDID
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public String getJcdid() {
        return jcdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDJC_KGGZTDDY_DATA.JCDID
     *
     * @param jcdid the value for DDJC_KGGZTDDY_DATA.JCDID
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public void setJcdid(String jcdid) {
        this.jcdid = jcdid == null ? null : jcdid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDJC_KGGZTDDY_DATA.SAVE_PATH
     *
     * @return the value of DDJC_KGGZTDDY_DATA.SAVE_PATH
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public String getSavePath() {
        return savePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDJC_KGGZTDDY_DATA.SAVE_PATH
     *
     * @param savePath the value for DDJC_KGGZTDDY_DATA.SAVE_PATH
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public void setSavePath(String savePath) {
        this.savePath = savePath == null ? null : savePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDJC_KGGZTDDY_DATA.FHDL
     *
     * @return the value of DDJC_KGGZTDDY_DATA.FHDL
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public String getFhdl() {
        return fhdl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDJC_KGGZTDDY_DATA.FHDL
     *
     * @param fhdl the value for DDJC_KGGZTDDY_DATA.FHDL
     *
     * @mbggenerated Fri Nov 16 16:13:35 CST 2018
     */
    public void setFhdl(String fhdl) {
        this.fhdl = fhdl == null ? null : fhdl.trim();
    }
}