package com.lnsoft.module.pms.mapper;

import com.lnsoft.module.pms.pojo.TSbDysbDyxl;
import com.lnsoft.module.pms.pojo.TSbDysbDyxlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSbDysbDyxlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SB_DYSB_DYXL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    int countByExample(TSbDysbDyxlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SB_DYSB_DYXL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    int deleteByExample(TSbDysbDyxlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SB_DYSB_DYXL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    int deleteByPrimaryKey(String objId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SB_DYSB_DYXL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    int insert(TSbDysbDyxl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SB_DYSB_DYXL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    int insertSelective(TSbDysbDyxl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SB_DYSB_DYXL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    List<TSbDysbDyxl> selectByExample(TSbDysbDyxlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SB_DYSB_DYXL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    TSbDysbDyxl selectByPrimaryKey(String objId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SB_DYSB_DYXL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") TSbDysbDyxl record, @Param("example") TSbDysbDyxlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SB_DYSB_DYXL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    int updateByExample(@Param("record") TSbDysbDyxl record, @Param("example") TSbDysbDyxlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SB_DYSB_DYXL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    int updateByPrimaryKeySelective(TSbDysbDyxl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SB_DYSB_DYXL
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    int updateByPrimaryKey(TSbDysbDyxl record);
}