package com.lnsoft.module.pms.mapper;

import com.lnsoft.module.pms.pojo.TSbZlsbTbsfz;
import com.lnsoft.module.pms.pojo.TSbZlsbTbsfzExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSbZlsbTbsfzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SB_ZLSB_TBSFZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    int countByExample(TSbZlsbTbsfzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SB_ZLSB_TBSFZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    int deleteByExample(TSbZlsbTbsfzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SB_ZLSB_TBSFZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    int deleteByPrimaryKey(String objId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SB_ZLSB_TBSFZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    int insert(TSbZlsbTbsfz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SB_ZLSB_TBSFZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    int insertSelective(TSbZlsbTbsfz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SB_ZLSB_TBSFZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    List<TSbZlsbTbsfz> selectByExample(TSbZlsbTbsfzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SB_ZLSB_TBSFZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    TSbZlsbTbsfz selectByPrimaryKey(String objId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SB_ZLSB_TBSFZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") TSbZlsbTbsfz record, @Param("example") TSbZlsbTbsfzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SB_ZLSB_TBSFZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    int updateByExample(@Param("record") TSbZlsbTbsfz record, @Param("example") TSbZlsbTbsfzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SB_ZLSB_TBSFZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    int updateByPrimaryKeySelective(TSbZlsbTbsfz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SB_ZLSB_TBSFZ
     *
     * @mbggenerated Fri Nov 16 15:13:00 CST 2018
     */
    int updateByPrimaryKey(TSbZlsbTbsfz record);
}