package com.lnsoft.module.pms.mapper;

import com.lnsoft.module.pms.pojo.TZhZtjxSyxm;
import com.lnsoft.module.pms.pojo.TZhZtjxSyxmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TZhZtjxSyxmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZH_ZTJX_SYXM
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    int countByExample(TZhZtjxSyxmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZH_ZTJX_SYXM
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    int deleteByExample(TZhZtjxSyxmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZH_ZTJX_SYXM
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    int deleteByPrimaryKey(String objId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZH_ZTJX_SYXM
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    int insert(TZhZtjxSyxm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZH_ZTJX_SYXM
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    int insertSelective(TZhZtjxSyxm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZH_ZTJX_SYXM
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    List<TZhZtjxSyxm> selectByExample(TZhZtjxSyxmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZH_ZTJX_SYXM
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    TZhZtjxSyxm selectByPrimaryKey(String objId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZH_ZTJX_SYXM
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") TZhZtjxSyxm record, @Param("example") TZhZtjxSyxmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZH_ZTJX_SYXM
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    int updateByExample(@Param("record") TZhZtjxSyxm record, @Param("example") TZhZtjxSyxmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZH_ZTJX_SYXM
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    int updateByPrimaryKeySelective(TZhZtjxSyxm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZH_ZTJX_SYXM
     *
     * @mbggenerated Fri Nov 16 15:12:59 CST 2018
     */
    int updateByPrimaryKey(TZhZtjxSyxm record);
}